// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWlypoMsWMrhcxAdNZHlPMIbxJ4BfmCTs',
    appId: '1:670103320817:web:333da70eb18dc952b19150',
    messagingSenderId: '670103320817',
    projectId: 'attendanceapp-a6853',
    authDomain: 'attendanceapp-a6853.firebaseapp.com',
    storageBucket: 'attendanceapp-a6853.appspot.com',
    measurementId: 'G-ZGGWLY12JT',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlypoMsWMrhcxAdNZHlPMIbxJ4BfmCTs',
    appId: '1:670103320817:web:333da70eb18dc952b19150',
    messagingSenderId: '670103320817',
    projectId: 'attendanceapp-a6853',
    authDomain: 'attendanceapp-a6853.firebaseapp.com',
    storageBucket: 'attendanceapp-a6853.appspot.com',
    measurementId: 'G-ZGGWLY12JT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIrnhgvjfCgsCbYjTaG-vEj6zJsp4iHU',
    appId: '1:670103320817:ios:3468f86c85974ee7b19150',
    messagingSenderId: '670103320817',
    projectId: 'attendanceapp-a6853',
    storageBucket: 'attendanceapp-a6853.appspot.com',
    iosBundleId: 'com.terkage.attendanceapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIrnhgvjfCgsCbYjTaG-vEj6zJsp4iHU',
    appId: '1:670103320817:ios:3468f86c85974ee7b19150',
    messagingSenderId: '670103320817',
    projectId: 'attendanceapp-a6853',
    storageBucket: 'attendanceapp-a6853.appspot.com',
    iosBundleId: 'com.terkage.attendanceapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARe4jhXum6mu5R7P7CTbhd5Gj4H0QOzeY',
    appId: '1:670103320817:android:9340aefadc7c7c25b19150',
    messagingSenderId: '670103320817',
    projectId: 'attendanceapp-a6853',
    storageBucket: 'attendanceapp-a6853.appspot.com',
  );

}