// ////List of Department
// //final Department = ["Strategic_Information", "Care&Treatment"];
//
// final Administration = {
//   "1": "Principal Manager",
//   "2": "Asset Manager",
//   "3": "Admin Officer",
//   "4": "Admin Associate",
//   "5": "Admin Assistant",
//   "6": "Senior Manager-Admin",
//   "7": "ICT Associate",
//   "8": "Senior Manager-Logistics",
//   "9": "Logistics Associate",
// };
//
// final CareAndTreatment = {
//   "1": "Associate Director",
//   "2": "Senior Advisor-Adult ART",
//   "3": "Senior Advisor-Pediatric",
//   "4": "Senior Advisor-TB/HIV",
//   "5": "Advisor- PMTCT",
//   "6": "Advisor- C&T",
//   "7": "Senior Specialists- C&T",
//   "8": "Specialists-C&T",
//   "9": "Public Health Specialist",
//   "10": "Officer-C&T",
// };
//
// final Communications = {
//   "1": "Advisor",
//   "2": "Specialist",
//   "3": "Associate",
// };
//
// final Compliance = {
//   "1": "Advisor-Grants",
//   "2": "Senior Specialist-Grants",
//   "3": "Specialist-Grants",
//   "4": "Officer-Grants",
//   "5": "Associate-Grants",
// };
//
// final Finance = {
//   "1": "Head of Finance",
//   "2": "Manager-Management Accounting",
//   "3": "Manager-Financial Accounting",
//   "4": "Accountant-Management Accounting",
//   "5": "Accountant-Financial Accounting",
//   "6": "Senior Finance Officer",
//   "7": "Finance Associate",
// };
//
// final Sustainability = {
//   "1": "Program Advisor",
// };
//
// final Gender_And_Protection = {
//   "1": "Senior Specialist-G&P",
//   "2": "Officer-Gender&Protection",
// };
//
// final Health_Systems_Strengthening = {
//   "1": "Program Advisor",
// };
//
// final Human_Resource = {
//   "1": "Senior HR Manager",
//   "2": "HR Manager",
//   "3": "Senior HR Officer",
//   "4": "HR Officer",
//   "5": "HR Associate",
//   "6": "HR Assistant",
// };
//
// final Internal_Audit = {
//   "1": "Manager-Internal Audit",
//   "2": "Senior Officer",
// };
//
// final Knowledge_Management = {
//   "1": "Senior Specialist",
// };
//
// final Laboratory = {
//   "1": "Senior Advisor",
//   "2": "Advisor",
//   "3": "Advisor-Logistics",
//   "4": "Advisor-Equipment&AHD",
//   "5": "Senior Specialist",
//   "6": "Specialist",
//   "7": "Officer",
// };
//
// final OVC = {
//   "1": "Senior Advisor",
//   "2": "Senior Specialist",
//   "3": "Manager",
//   "4": "Officer- Economic Strengthening",
//   "5": "Officer-OVC Prevention",
//   "6": "Officer-MEAL",
//   "7": "Officer-Case Management",
// };
//
// final Pharmacy = {
//   "1": "Senior Advisor",
//   "2": "Advisor",
//   "3": "Senior Specialist",
//   "4": "Specialist",
//   "5": "Officer",
// };
//
// final Prevention = {
//   "1": "Senior Advisor",
//   "2": "Advisor",
//   "3": "Senior Specialist",
//   "4": "Specialists",
// };
//
// final Procurement = {
//   "1": "Procurement Manager",
//   "2": "Procurement Officer",
//   "3": "Procurement Associate",
// };
//
// final Programs = {
//   "1": "Senior Program Manager",
//   "2": "Program Manager",
//   "3": "Program Officer",
//   "4": "Program Associate",
//   "5": "Program Assistant",
// };
// final Program_Accountability = {
//   "1": "Senior Manager",
// };
//
// final Program_Management = {
//   "1": "Senior Advisor",
//   "2": "Advisor",
// };
//
// final State_Management = {
//   "1": "State Team Lead",
// };
//
// final Strategic_Information = {
//   "1": "Associate Director",
//   "2": "Advisor-Central Coordination",
//   "3": "Advisor-Central Coordination",
//   "4": "Advisor-DQA",
//   "5": "Advisor-MEAL-OVC",
//   "7": "Advisor-DB Management",
//   "8": "Associate-MEAL",
//   "9": "Assitant-MEAL",
//   "10": "Advisor-Hardware Management",
//   "11": "Advisor-Health Informatics",
//   "12": "Senior Specialist-MEAL",
//   "13": "Senior Specialist-HI",
//   "14": "Specialist-HI",
//   "15": "Specialists-MEAL",
//   "16": "Officer-MEAL",
//   "17": "Officer-HI",
//   "18": "Associate-HI",
//   "19": "Assitant-HI",
//   "20": "Associate-DB Management",
//   "21": "Assistant-DB Management",
//   "22": "Advisor-QI",
//   "23": "Specialist-QI",
//   "24": "Officer-QI",
//   "25": "Associate-QI",
//   "26": "Assitant-QI",
//   "27": "Advisor-Epid&Surveillance",
//   "28": "Specialist-Epid&Surveillance",
//   "29": "Associate-Epid&Surveillance",
//   "30": "Assitant-Epid&Surveillance",
// };
//
// final Transport_Management = {
//   "1": "Manager",
//   "2": "Officer",
//   "3": "Senior Assistant(Head Driver)",
//   "4": "Senior Assistants",
//   "5": "Assistants",
// };
//
// // List of Adhoc Directory
// final Care_and_Treatment = {
//   "1": "Clinical Associates",
//   "2": "Senior C&T Assistant",
// };
//
// final Preventions = {
//   "1": "ART Nurse",
//   "2": "HTS Assitant",
//   "3": "Tracking Assistant",
//   "4": "Adherence Counsellor",
// };
//
// final Lab = {
//   "1": "VL Champion",
// };
//
// final PharmLogistics = {
//   "1": "Pharm. Technician",
//   "2": "Pharm. Assistant",
// };
//
// final SI = {
//   "1": "SI Assistants",
//   "2": "Senior SIAs",
// };
//
// //List Of Projects
// final Projects = [
//   "ACCESS Project",
//   //
//   "ECHO SAHARA Project",
//   "GFFO Phase II Project",
//   "Norway MFA Project",
//   "NHF Project",
//   "B-SLiC Project",
//   "FAO Project",
//   "UNHCR-Agric/WASH",
//   "UNHCR-Protection",
//   "UNHCR-Migration",
//   "STEM Project",
//   "GLOBAL FUND",
//   "GOOD GOVERNANCE",
//   "INSTITUTIONAL CAPACITY",
//   "Research & Development",
//   "Catholic Parliamentary Liason"
// ];
//
// // Assuming 'Roles' is a list of strings representing roles
// List<String> Roles = ["User"];
//
// final StaffCategory = ["", "HQ/State Staff", "Facility Staff"];
//
// // List(Map) of Facilities in each state
// final Abia = {
//   "1": "Amasator ward",
//   "2": "Abia KP OSS",
//   "3": "ABSUTH",
//   "4": "Amachara GH",
//   "5": "Arochukwu GH",
//   "6": "CENTRAL MEDICAL CENTRE",
//   "7": "COTTAGE HOSP.,AZUMINI",
//   "8": "COTTAGE HOSP.,OWAZA",
//   "9": "Denokem Hosp.",
//   "10": "DMMMH",
//   "11": "FMC",
//   "12": "IHUNANYA HOSP.",
//   "13": "Isikwuato GH",
//   "14": "King of Kings Hosp.",
//   "15": "LIVINGWORD MISSION HOSP.",
//   "16": "MADONNA HOSP.",
//   "17": "MARIST COTTAGE HOSP.",
//   "18": "MENDEL Diag. HOSP.",
//   "19": "New Era Hosp.",
//   "20": "NIGERIA CHRISTIAN HOSP.",
//   "21": "NKECHI COLWILL METH. HOSP.",
//   "22": "Ohafia General Hosp.",
//   "23": "Okpuala Ngwa GH",
//   "24": "ROYAL CROSS METH. HOSP.",
//   "25": "SEMCON FRIENDS Hosp.",
//   "26": "SEVENTH DAY ADVENTIST HOSP.",
//   "27": "ST JOSEPH HOSP.",
//   "28": "ST ANTHONY HOSP.",
//   "29": "ST.CHARLES HOSP.",
//   "30": "ST.ANTHONY HOSP.",
//   "31": "TERESA ORSINI CLINIC",
//   "32": "Umu Nneochi GH",
// };
//
// final Adamawa = {
//   "1": "Adamawa Hosp.,Yola",
//   "2": "Borrong GH",
//   "3": "Boshang Clinic&Maternity",
//   "4": "Clinic B Girei",
//   "5": "Cottage Hosp. Gulak",
//   "6": "Fufore Cottage Hosp.",
//   "7": "Ganye GH",
//   "8": "Garkida GH",
//   "9": "GDCMH Ngurore",
//   "10": "Gurin PHC",
//   "11": "Guyuk GH",
//   "12": "Hong Cottage Hosp.",
//   "13": "Maiha Cottage Hosp.",
//   "14": "Major Aminu Urban Health Centre",
//   "15": "Mayo Belwa Cottage Hosp.",
//   "16": "Michika GH",
//   "17": "Mubi GH",
//   "18": "Numan GH",
//   "19": "Peace Hosp. Jimeta",
//   "20": "Shelleng NYSC Clinic",
//   "21": "Song Cottage Hosp",
//   "22": "St.Francis Hosp",
//   "23": "Toungo Cottage Hosp",
//   "24": "Township Clinic Jada",
//   "25": "Township Clinic Mayo-Belwa",
//   "26": "Wauro-Jabbe Health Centre",
//   "27": "Yola FMC",
//   "28": "Yola KP OSS",
//   "29": "Yola Specialist Hosp",
// };
//
// final AkwaIbom = {
//   "1": "aBase Abat PHC",
//   "2": "Abasi Ekeme Clinic",
//   "3": "Abiakpo Ikot Essien Health Centre",
//   "4": "Abiakpo Ntuen Health Post",
//   "5": "Achan Ika Health Centre",
//   "6": "Adadia Health Post",
//   "7": "Adiasim Health Centre",
//   "8": "Afaha Abia PHC",
//   "9": "Afaha Effiong OP Base Model PHC",
//   "10": "Afaha Eket Holifield Hosp",
//   "11": "Afaha Ikot Ebak PHC",
//   "12": "Afaha Obong PHC",
//   "13": "Afia Nsit PHC",
//   "14": "Aka Offot Health Centre",
//   "15": "Akai Ubium Cottage Hosp",
//   "16": "Akpautong Mt.Camel Hosp",
//   "17": "AKSU Medical Center",
//   "18": "Alma Clinic",
//   "19": "Amanyam PHC",
//   "20": "Asang Nsit PHC",
//   "21": "Base Ikot Abasi PHC",
//   "22": "Base Urue Offong PHC",
//   "23": "Caleb(Miracle)Medical Center",
//   "24": "Cedar&Olive Clinic",
//   "25": "Confidence Maternity",
//   "26": "Cottag Hosp",
//   "27": "Dammy Memorial Hosp",
//   "28": "Dan Abia Specialist Clinic",
//   "29": "Demak Clinic",
//   "30": "Diamond Clinic",
//   "31": "Dyme Hosp.&Maternity",
//   "32": "Ebom PHC",
//   "33": "Ebughu PHC",
//   "34": "Ediene I Health Centre",
//   "35": "Effoi PHC",
//   "36": "Eket Immanuel GH",
//   "37": "Eket KP OSS",
//   "38": "Ekparakwa Health Centre",
//   "39": "Ekpene Ibia PHC",
//   "40": "Ekpene Obo Cottage Hosp",
//   "41": "Ekpene Obom QIC Rehab Hosp",
//   "43": "Ekpenyong 1 Midim Atan Health Centre",
//   "44": "Ememobong Maternity",
//   "45": "Enwang PHC",
//   "46": "Esin U0ot PHC",
//   "47": "Etim Ekpo GH",
//   "48": "Etim Ekpo PHC",
//   "49": "Etinan GHC",
//   "50": "Etinan PHC",
//   "51": "Etip Ediene PHC",
//   "52": "Evergreen Medical Centre",
//   "53": "Eweme Model PHC",
//   "54": "Eyo Abasi Health Post",
//   "55": "Eyo Okponung PHC",
//   "56": "Eyofin PHC",
//   "57": "Faith Medical Centre",
//   "58": "Family Foundation Clinic",
//   "59": "First Line Clinics&Surgery",
//   "60": "Fletcher Memorial Hosp.",
//   "61": "Gateway Hosp.",
//   "62": "General Hosp. Mbioto",
//   "63": "Good Clinic",
//   "64": "Health Confidence Centre",
//   "65": "Ibaka PHC",
//   "66": "Ibeno Cottage Hosp",
//   "67": "Ibiaku Isshiet PHC",
//   "68": "Ibiaku PHC(BASE)",
//   "69": "Ibiaku-Uruan PHC",
//   "70": "Ibiono Handmaids Hosp.",
//   "71": "Ibiono Palmer Memorial Hosp",
//   "72": "Ibotong Health Post",
//   "73": "Idoro Obio Health Centre",
//   "74": "Idua Assang Health Post",
//   "75": "Idung Assan Health Centre",
//   "76": "Idu-Uruan PHC",
//   "77": "Ifa Atai Health Post",
//   "78": "Ifa Ikot Health Centre",
//   "79": "Iko Eket Health Centre",
//   "80": "Iko Otu Health Centre",
//   "81": "Iko Town PHC",
//   "82": "Ikono GH",
//   "83": "Ikot Abasi GH",
//   "84": "Ikot Abia Cottage Hosp.",
//   "85": "Ikot Adaidem PHC",
//   "86": "Ikot Akpa Ntuk PHC",
//   "87": "Ikot Akpan Anwa PHC",
//   "88": "Ikot Akpan Effia Health Centre",
//   "89": "Ikot Akpan Essien Health Centre",
//   "90": "Ikot Akpan Ikpong Health Centre",
//   "91": "Ikot&em Itam PHC",
//   "92": "Ikot Annang PHC",
//   "93": "Ikot Ayan Ikono PHC",
//   "94": "Ikot Ebak Poly Clinic",
//   "95": "Ikot Ebo Health Centre",
//   "96": "Ikot Ebo Ikono PHC",
//   "97": "Ikot Edebe Health Centre",
//   "98": "Ikot Eko Ibon GH",
//   "99": "Ikot Ekpaw Cottage Hosp",
//   "100": "Ikot Ekpene General Hosp",
//   "101": "Ikot Ekpene Infectious Disease Hosp",
//   "102": "Ikot Ekpene PHC",
//   "103": "Ikot Ekpene Udo Cottage Hosp",
//   "104": "Ikot Ekwere Model PHC",
//   "105": "Ikot Epkene KP OSS",
//   "106": "Ikot Esenam Health Centre",
//   "107": "Ikot Etok Udo PHC",
//   "108": "Ikot Idaha PHC",
//   "109": "Ikot Ide Health Centre",
//   "110": "Ikot Idem Udo PHC",
//   "111": "Ikot Iko Health Centre",
//   "112": "Ikot Inyang Health Post",
//   "113": "Ikot Obio Edim Health Centre",
//   "114": "Ikot Obio Inyang PHC",
//   "115": "Ikot Okoro General Hosp",
//   "116": "Ikot Okubo PHC",
//   "117": "Ikot Otoenyie Health Post",
//   "118": "Ikot Out Health Centre",
//   "119": "Ikot Udoe Health Centre",
//   "120": "Ikot Udom Maternal&Child Centre",
//   "121": "Ikot Utu Model PHC",
//   "122": "Ikpa Ikot Uneke PHC",
//   "123": "Ikpe Annang GH",
//   "124": "Ikpe Annang Health Centre",
//   "125": "Ikpe Ikot Nkon GH",
//   "126": "Ikpe Oro Health Post",
//   "127": "Ima Abasi Maternity Home",
//   "128": "IMOMC Ibesikpo Asutan",
//   "129": "Inua Eyet Ikot Health Post",
//   "130": "Ituk Mbang Methodist GH",
//   "131": "Iwerre Health Centre",
//   "132": "Iwuo Achang Health Post",
//   "133": "Jafaar Clinic Ndon Eyon",
//   "134": "LifeCare Clinic",
//   "135": "Mainland Clinic",
//   "136": "Marickson Hosp.",
//   "137": "Mary Slessor GH",
//   "138": "Mbak Atai Operational Base PHC",
//   "139": "Mbak Etoi PHC",
//   "140": "Mbia Obong Ikot Udofia PHC",
//   "141": "Mbiabong Itam Health Center",
//   "142": "Mbiabong PHC",
//   "143": "Mbiaso PHC",
//   "144": "Mbiaya CHC",
//   "145": "Mbiokporo I Model PHC",
//   "146": "Mbokpu Oduobo PHC",
//   "147": "Mbokpu-Eyoakan Health Centre",
//   "148": "Mercy Hosp.",
//   "149": "Mercy Hosp.",
//   "150": "Mfon-Abasi Clinic",
//   "151": "Midim Abak Health Centre",
//   "152": "Mkpanak PHC",
//   "153": "Mkpat Enin PHC",
//   "154": "Mkpok Health Centre",
//   "155": "Mount Olive Clinic&Maternity",
//   "156": "NCI Medical Centre",
//   "157": "Ndon Ebom PHC",
//   "158": "Ndon Utim PHC",
//   "159": "Nissi Specialist Hosp.",
//   "160": "Nkim Itam Health Centre",
//   "161": "Nkot Ekpene CHC",
//   "162": "Northern Afaha Health Centre",
//   "163": "Nsan Health Centre",
//   "164": "Nsit Atai PHC",
//   "165": "Nsit Ubium PHC",
//   "166": "Nsit Ubium PHC",
//   "167": "Ntak Inyang Model PHC",
//   "168": "Ntan Ibiono Eduwem Clinic",
//   "169": "Nto Edino CHC",
//   "170": "Nto Edino PHC",
//   "171": "Nto Eton Health Post",
//   "172": "Nto Etuk Udo Health Centre",
//   "173": "Nung Udoe Model PHC",
//   "174": "Nung Udoe PHC",
//   "175": "Nung Ukim Health Centre",
//   "176": "Nwaniba PHC",
//   "177": "Oboetim Ikot Ekang PHC",
//   "178": "Obot Akara PHC",
//   "179": "Odobo Health Centre",
//   "180": "Odoro Ikpe Operational Base ",
//   "181": "Oduonim Health Post",
//   "182": "Okobo GH",
//   "183": "Okopedi PHC",
//   "184": "Oku Model Health Centre Uyo",
//   "185": "Oniong PHC",
//   "186": "Onna CHC",
//   "187": "Operational Base PHC",
//   "188": "Oron Christ Victory Medical Centre",
//   "189": "Oron Eket CHC",
//   "190": "Oron GH(Iquita)",
//   "191": "Oron KP OSS- Virtual",
//   "192": "Oruk Anam PHC",
//   "193": "Oruko GH",
//   "194": "Oruko PHC",
//   "195": "Oti Oro PHC",
//   "196": "Our Lady of Lourdes Infirmary",
//   "197": "Oyoku Ibighi Health Centre",
//   "198": "PHC Upenekang",
//   "199": "Precious Seed Clinic",
//   "200": "Premier Medical Centre",
//   "201": "Priscon Clinic",
//   "202": "Redemption Medical Centre",
//   "203": "Sheltered Specialist Hosp.",
//   "204": "St Patricks Clinic",
//   "205": "St.Lukes Hosp. Anua",
//   "206": "St.Mary's Hosp.",
//   "207": "Ubong Abasi Specialist Clinic",
//   "208": "Uda Health Centre",
//   "209": "Uduak Abasi Clinic",
//   "210": "Ukana Cottage Hosp.",
//   "211": "Ukana East PHC",
//   "212": "Ukana Iba St Josephs rehab Center",
//   "213": "Ukpom Abak GH",
//   "214": "Ukpom Edem Inyang PHC",
//   "215": "Ukpom-Ikono PHC",
//   "216": "University of Uyo Medical Centre",
//   "217": "University of Uyo Youth Friendly Centre",
//   "218": "UNTHosp",
//   "219": "Unwana Family Hosp.",
//   "220": "Uquo PHC",
//   "221": "Urua Inyang PHC",
//   "222": "Urua Obo Health post",
//   "223": "Use Abat St.Theresa's Hosp.",
//   "224": "Use PHC",
//   "225": "Usuk Ibakasi PHC",
//   "226": "Utibe Ima Medical Centre",
//   "227": "Utibe-Abasi Clinic",
//   "228": "Utine Nduong Health Centre",
//   "229": "Utu Edem Usung Health Post",
//   "230": "Utu Etim Ekpo Divine Love Hosp.",
//   "231": "UUTH CHC Ikot Akpamba",
//   "232": "Uwakmfon Specialist Hosp.",
//   "233": "Uwem Foundation Specialist Hosp.",
//   "234": "Uya Oro Health Post",
//   "235": "Uyenghe PHC",
//   "236": "Uyo Base PHC",
//   "237": "Uyo Heartland Alliance Community Centre",
//   "238": "Uyo HIV Counselling&Teasting Centre",
//   "239": "Uyo Police Hosp.",
//   "240": "Uyo Saman Clinic",
//   "241": "Uyo St Athanasius Medical Centre",
//   "242": "West Itam Public Health Center",
//   "243": "Zoe Consultants Hosp.",
// };
//
// final Anambra = {
//   "1": "Abubor Nnewichi Obioma Specialist Hosp.",
//   "2": "Adazi St Joseph Hosp.",
//   "3": "Adazi St Joseph Hosp.",
//   "4": "Aguata PHC",
//   "5": "Aguleri Immaculate Heart Hosp.",
//   "6": "Aguleri Immaculate Heart Hosp.",
//   "7": "Amichi Diocesan Hosp.",
//   "8": "Amichi Diocesan Hosp.",
//   "9": "Anambra State OSS(OSS),Awka",
//   "10": "Anambra State UNTHosp",
//   "11": "Apex Medical Centre",
//   "12": "Awka Faith Hosp.",
//   "13": "Awkuzu PHC",
//   "14": "Cath. Visitation Hosp.&Maternity,Umuchu",
//   "15": "CHC Osumorghu",
//   "16": "Chidera Model Hosp.&Maternity Home",
//   "17": "Chuwuemeka Odumegwu Ojukwu UNTHosp",
//   "18": "Delta Hosp.&Maternity",
//   "19": "Ebenesi Nnobi PHC",
//   "20": "Ekwulobia GH",
//   "21": "Ekwulobia GH",
//   "22": "Enugu-Ukwu GH",
//   "23": "Evans Specialist Hosp.",
//   "24": "Eziani Health Centre",
//   "25": "Faith Hosp.&Maternity,Awka",
//   "26": "GH Nimo",
//   "27": "GH Orumba",
//   "28": "GH Osomalla",
//   "29": "God is able Maternity Home",
//   "30": "Goodnews Hosp.&Maternity",
//   "31": "Holy Rosary Hosp.",
//   "32": "Holy Rosary Hosp.",
//   "33": "Igboukwu Diocesan Hosp.",
//   "34": "Igboukwu Diocesan Hosp.",
//   "35": "Immaculate Heart Hosp.(Nkpor)",
//   "36": "Immaculate Heart Hosp.(Nkpor)",
//   "37": "Iyi-Enu Hosp.",
//   "38": "Iyi-Enu Hosp.",
//   "39": "Kandudi Specialist Hosp.",
//   "40": "Madueke Memorial Hosp.&Maternity",
//   "41": "Model PHC Umunna",
//   "42": "Neni CHC NAUTH",
//   "43": "Neni CHC NAUTH",
//   "44": "Nkpor Crown Hosp.&Maternity",
//   "45": "Nkpor Crown Hosp. Maternity",
//   "46": "Nnamdi Azikiwe UNTHosp",
//   "48": "Nnewi Diocesan Hosp.",
//   "49": "Nnewi Diocesan Hosp.",
//   "50": "Nnobi Chukwunonso Hosp.&Maternity",
//   "51": "Nwobi Memorial Hosp.",
//   "52": "Oba CHC(Trauma Centre)",
//   "53": "Oba CHC(Trauma Centre)",
//   "54": "Obosi St Martins Hosp.",
//   "55": "Obosi St Martin's Hosp.",
//   "56": "Ojoto-Obofia PHC",
//   "57": "Ojotu Uno PHC",
//   "58": "Oko Community Hosp.",
//   "59": "Okpoko Kings Kidd Hosp.&Maternity",
//   "60": "Okpoko St Luke's Diocesan Hosp.",
//   "61": "Okpoko St Luke's Diocesan Hosp.",
//   "62": "Onitsha Basic PHC",
//   "63": "Onitsha GH",
//   "64": "Onitsha Pieta Hosp.",
//   "65": "Onitsha Pieta Hosp.",
//   "66": "Orafite GH",
//   "67": "Orafite GH",
//   "68": "Osumenyi Visitation Hosp.",
//   "69": "Osumenyi Visitation Hosp.",
//   "70": "Otolo Nnewi Chidiera Hosp.",
//   "71": "Otolo Umuenem PHC",
//   "72": "Our Lady of Lourdes Hosp.",
//   "73": "Our Lady of Lourdes Hosp.",
//   "74": "Ozubulu St.Jude Hosp.&Maternity",
//   "75": "Patricia Memorial Hosp.&Maternity Aka baby",
//   "76": "PHC Abagana",
//   "77": "PHC Achalla",
//   "78": "PHC Amaokpala",
//   "79": "PHC Amawbia",
//   "80": "PHC Ezeawulu",
//   "81": "PHC Iruzu ukpor",
//   "82": "PHC Isuaniocha",
//   "83": "PHC Mgbakwu",
//   "84": "PHC Nawfia",
//   "85": "PHC Ogboeye",
//   "86": "PHC Okpoko",
//   "87": "PHC Ukwulu",
//   "88": "PHC Umuanugo",
//   "89": "Praises Health Care Madam Denco Clinic",
//   "90": "Regina Caeli Hosp.",
//   "91": "Regina Caeli Hosp.,Awka",
//   "92": "Rise Clinic,Adazi Ani",
//   "93": "Rushgreen Hosp.",
//   "94": "St Charles Borromeo Hosp.",
//   "95": "St Charles Borromeo Hosp.",
//   "96": "Trinity Hosp.&Maternity",
//   "97": "Ukpo CHC",
//   "98": "Ukpo CHC",
//   "99": "Ukpor GH",
//   "100": "Umuchu Visitation Hosp.",
//   "101": "Umudim Life Specialist Hosp.&Maternity",
//   "102": "Umueri Diocesan Hosp.&Maternity",
//   "103": "Umueri Diocesan Hosp.&Maternity",
//   "104": "Umueri GH",
//   "105": "Umueze Anam PHC",
//   "106": "Umuhu Ubahu Okija PHC",
//   "107": "Umunya CHC",
//   "108": "Umunya CHC(NAUTH)",
//   "109": "Umunze Immaculate Heart Hosp.",
//   "110": "Umunze Immaculate Heart Hosp.",
//   "111": "Zenith Hosp.&Maternity",
// };
//
// final Bauchi = {
//   "1": "Abubakar Tafawa Balewa UNTHosp",
//   "2": "Alkaleri GH",
//   "3": "Apple Clinic",
//   "4": "Azare FMC",
//   "5": "Azare GH",
//   "6": "Azare GH",
//   "7": "ba Ningi GH",
//   "8": "Bauchi KP OSS",
//   "9": "Bayara Infectious Diseases Hosp.",
//   "10": "Bogoro GH",
//   "11": "Bogoro Maternal&Child Clinic",
//   "12": "Burra GH",
//   "13": "bWarji GH",
//   "14": "Dambam GH",
//   "15": "Darazo GH",
//   "16": "Dass GH",
//   "17": "Gamawa GH",
//   "18": "Giade GH",
//   "19": "Giade Maternal&Child Clinic",
//   "20": "Itas GH",
//   "21": "Jama are GH",
//   "22": "Kafin Madaki GH",
//   "23": "Katagum Zaki GH",
//   "24": "Lere PHC",
//   "25": "Mararraba PHC",
//   "26": "Misau GH",
//   "27": "Ni ima Consultant",
//   "28": "Pohlycon Clinic",
//   "29": "Reemee Clinic",
//   "30": "Shira Yana GH",
//   "31": "State Low Cost PHC",
//   "32": "Tafawa-Balewa GH",
//   "33": "Toro GH",
//   "34": "Urban Maternity",
//   "35": "Wuntin Dada Maternal&Child Clinic",
//   "36": "Yalwan Kagadama PHC",
// };
//
// final Bayelsa = {
//   "1": "Agudama Ekpetima(Hub) GH",
//   "2": "Agudama Tobis Clinic&Consultants",
//   "3": "Aleibiri Cottage Hosp.",
//   "4": "Amassoma GH ",
//   "5": "Diete-Koki Memorial Specialist Hosp.Yenegoa",
//   "6": "Ebedebiri Cottage Hosp.",
//   "7": "Family Support Program Clinic",
//   "8": "Grand Care Hosp.,Edepie",
//   "9": "Igbogene TB&Leprosy Referral Centre",
//   "10": "Inri Etekwe Glory Land",
//   "11": "Kolo GH",
//   "12": "Kpansia Asueife New Life Hosp.",
//   "13": "Landmark Medical Centre",
//   "14": "Mercy&Favour Clinic&Diagonistic Center,Polaku",
//   "15": "Nembe GH",
//   "16": "New Survivor Hosp.,Igbo-Gene",
//   "17": "Niger Delta UNTHosp",
//   "18": "Okpoama Cottage Hosp.",
//   "19": "Olugbobiri CHC",
//   "20": "Otuasega Cottage Hosp.",
//   "21": "Peremabiri Cottage Hosp.",
//   "22": "Sagbama GH",
//   "23": "St.George Hosp.,Okutukutu",
//   "24": "Twon-Brass GH",
//   "25": "Yenagoa FMC",
//   "26": "Yenagoa OSS",
// };
//
// final Benue = {
//   "1": "36 Matyrs Clinic- Mbape",
//   "2": "Aba Health Centre",
//   "3": "Abakor PHC",
//   "4": "Abeda PHC",
//   "5": "Abeda Shittille PHC",
//   "6": "Abiam Family Support Program Clinic",
//   "7": "Abinisi PHC",
//   "8": "Aboho PHC",
//   "9": "Adi CHC",
//   "10": "Adikpo GH",
//   "11": "Adikpo Katsina-Ala PHC",
//   "12": "Afia CHC",
//   "13": "Agbeede PHC",
//   "14": "Agidi PHC",
//   "15": "Agwabi PHC",
//   "16": "AHOEBEE MEMMORIAL Hosp.",
//   "17": "Akaa PHC",
//   "18": "Akerior CHC",
//   "19": "Akpagher PHC",
//   "20": "Akputu  PHC",
//   "21": "Akumator Health Centre",
//   "22": "Aliade CHC",
//   "23": "Aliade GH",
//   "24": "Amafor PHC",
//   "25": "Anonghul PHC",
//   "26": "Anvambe PHC",
//   "27": "Anyiin PHC",
//   "28": "Anzembe Clinic",
//   "29": "Aondana Clinic",
//   "30": "Asambe PHC",
//   "31": "Asiasa PHC",
//   "32": "Aso CHC",
//   "33": "Asukunya PHC",
//   "34": "Atekombo CHC",
//   "35": "Aterayange CHC",
//   "36": "Atighir LGA Health Center",
//   "37": "Atuna Clinic&Maternity",
//   "38": "Avaa Gbande Memorial Clinic&Maternity",
//   "39": "Awajir PHC",
//   "40": "Ayaka PHC",
//   "41": "Ayati PHC",
//   "42": "Ayilamo PHC",
//   "43": "Baki Clinic",
//   "44": "Baki Clinic",
//   "45": "be Ado",
//   "46": "be Agatu",
//   "47": "be Apa",
//   "48": "be Buruku",
//   "49": "be Gboko",
//   "50": "be Gboko GH",
//   "51": "be Guma",
//   "52": "be Gwer East",
//   "53": "be Gwer West",
//   "54": "be Katsina-Ala",
//   "55": "be Katsina-Ala GH",
//   "56": "be Konshisha",
//   "57": "be Kwande",
//   "58": "be Logo",
//   "59": "be Madonna Hosp.",
//   "60": "be Mkd",
//   "61": "be Obi",
//   "62": "be Ogbadibo",
//   "63": "be Ohimini",
//   "64": "be Oju",
//   "65": "be Okpokwu",
//   "66": "be Otukpo",
//   "67": "be Tarka",
//   "68": "be Ukum",
//   "69": "be Ushongo",
//   "70": "be Vandeikya",
//   "71": "Benue State UNTHosp",
//   "72": "Bethesda Hosp.-Ikachi",
//   "73": "Bishop Murray Medical Center",
//   "74": "Bonta Family Support Program Clinic",
//   "75": "Central Hosp. Anyiin",
//   "76": "CHC Abenga",
//   "77": "CHC Agasha",
//   "78": "CHC Unzughul",
//   "79": "Chito LGA Health Center",
//   "80": "City Hosp.",
//   "81": "Convenant Clinic",
//   "82": "Cottage Hosp.",
//   "83": "CRCN Abinsi",
//   "84": "Dangote clinic",
//   "85": "Dio PHC",
//   "86": "Doodoo Clinic",
//   "87": "Dooshima PHC",
//   "88": "Dooter Clinic",
//   "89": "El Shaddai Clinic-Achocho",
//   "90": "European Economic Community Clinic",
//   "91": "Farmter Clinic Abeda",
//   "92": "FMC-Mkd",
//   "93": "Fr. Mathias Clinic",
//   "94": "FSP Agan",
//   "95": "FSP Daudu",
//   "96": "FSP UYOOR",
//   "97": "FSP Yogbo",
//   "98": "Gabriel Suswam Cottage Hosp.",
//   "99": "Gbise PHC",
//   "100": "Gboko East CHC",
//   "101": "Gboko KP OSS",
//   "102": "Gbor CHC",
//   "103": "Gboragayo PHC",
//   "104": "GH Buruku",
//   "105": "GH Naka",
//   "106": "GH Gbajimba",
//   "107": "Gonduzua PHC",
//   "108": "Grace Cottage Hosp.",
//   "109": "Gums KP OSS",
//   "110": "Gwarche PHC",
//   "111": "Gwer East KP OSS",
//   "112": "Gwer West KP OSS",
//   "113": "Hegha CHC",
//   "114": "Helen Clinic&Maternity",
//   "115": "Hemko Hosp.",
//   "116": "Herb Fisher wellness Clinic",
//   "117": "Holy Child Clinic&Maternity",
//   "118": "HOLY CROSS Hosp.",
//   "119": "Holy Name Clinic-Ugbokolo",
//   "120": "Hope Hosp.",
//   "121": "Hope Hosp.-Gungul",
//   "122": "HOSSANA Hosp.",
//   "123": "Hwembe CHC",
//   "124": "Icheen Clinic&Maternity",
//   "125": "Idekpa GH",
//   "126": "Igbabaka PHC",
//   "127": "Igboughol LGA Clinic",
//   "128": "Igbughul PHC",
//   "129": "Igumale GH",
//   "130": "Ihotu Clinic&Maternity",
//   "131": "Ijadoga Otukpa GH",
//   "132": "Ikpaukur LGA Health Center",
//   "133": "Ikpayongo PHC",
//   "134": "Ikumbur Memorial clinic",
//   "135": "Ikyo PHC",
//   "136": "Immaculate Hosp.",
//   "137": "Iorna Clinic",
//   "138": "Iorza PHC",
//   "139": "Jimba PHC",
//   "140": "Jingir PHC",
//   "141": "Jirgba PHC",
//   "142": "Jolua Hosp.",
//   "143": "Jor Maternal&Child Clinic",
//   "144": "Jordan Clinic&Maternity",
//   "145": "Jou Mbatyough PHC",
//   "146": "Kafa Clinic",
//   "147": "Kartyo CHC",
//   "148": "Kator Clinic",
//   "149": "Katsina Ala KP OSS",
//   "150": "King Cross Clinic&Maternity",
//   "151": "King of Kings Clinic&Maternity",
//   "152": "Konshisha KP OSS",
//   "153": "Korinya PHC",
//   "154": "Kpe-Ambila PHC",
//   "155": "KPIF Mkd OSS",
//   "156": "Kur PHC",
//   "157": "Kwashon PHC",
//   "158": "Kyado PHC",
//   "159": "Leke Clinic&Maternity",
//   "160": "Lessel GH",
//   "161": "LG Clinic Gboko East",
//   "162": "LGHC AMAHUNDU",
//   "163": "LGHC Gbe",
//   "164": "LGHC Wende",
//   "165": "Live Clinic",
//   "166": "Logo KP OSS",
//   "167": "Lord Is Saviour Clinic&Maternity",
//   "168": "Luter Clinic",
//   "169": "Madina clinic",
//   "170": "Mkd Family Support Program Clinic",
//   "171": "Mkd KP OSS",
//   "172": "Manyam PHC",
//   "173": "Maranatha Clinic Ugba",
//   "174": "May Memorial Hosp.",
//   "175": "Mayange PHC",
//   "176": "Mba Agbanaya PHC",
//   "177": "Mba Agberabu PHC",
//   "178": "Mbaakem Health Centre",
//   "179": "Mbagen Community Hosp.-Abwa",
//   "180": "Mbaier Health Centre",
//   "181": "Mbalosu PHC",
//   "182": "Mbasar PHC",
//   "183": "Mbashija PHC",
//   "184": "Mbaton PHC",
//   "185": "Mbatyula Local Goverment Health Centre",
//   "186": "Mchia LGA Health Center",
//   "187": "Melabu CHC",
//   "188": "Mercy Hosp.",
//   "189": "Mhen Clinic Jov-Mbavaa",
//   "190": "Mimi Clinic&Maternity",
//   "191": "Mimidoo Clinic&Maternity-Gungul",
//   "192": "MPHC OPAHA",
//   "193": "Multicare Hosp.",
//   "194": "Mwar clinic",
//   "195": "Myom Hosp.-Gboko",
//   "196": "Nagu PHC",
//   "197": "Nahuta Hosp.",
//   "198": "Nakar Gwer West CHC",
//   "199": "Ndele PHC",
//   "200": "Nguher Clinic",
//   "201": "NKST Awambe",
//   "202": "NKST Ikpa PHC",
//   "203": "NKST Kuhe PHC",
//   "204": "NKST Clinic-Ishua",
//   "205": "NKST Clinic-Wannune",
//   "206": "NKST Clinic -Aku",
//   "207": "NKST CHC-Garagbohol",
//   "208": "NKST CHC-Isherev",
//   "209": "NKST Health Center-Gbe",
//   "210": "NKST Health Center-Lessel",
//   "211": "NKST Health Center-Uchi",
//   "212": "NKST Hosp.-Anyiin",
//   "213": "NKST Hosp.-Jato Aka",
//   "214": "NKST Hosp.-Mbaakon",
//   "215": "NKST Hosp.-Mkar",
//   "216": "NKST Hosp.-Sai",
//   "217": "NKST Hosp.- Zaki Biam",
//   "218": "NKST PHC-Ahobee",
//   "219": "NKST PHC-Anber",
//   "220": "NKST PHC-Biliji",
//   "221": "NKST PHC-Kasar",
//   "222": "NKST PHC-Pervkyaa",
//   "223": "Northbank GH",
//   "224": "Numbeve PHC",
//   "225": "Nyam Ugbeh Clinic",
//   "226": "Nyitar LGA Health Center",
//   "227": "Obarike-Ito GH",
//   "228": "Obi KP OSS",
//   "229": "OHE-OBE CLINIC",
//   "230": "Oju GH",
//   "231": "Oju KP OSS",
//   "232": "Okopga GH",
//   "233": "Onmba Aondo CHC",
//   "234": "Oostra-Gum Clinic&Maternity",
//   "235": "Otia Hosp.-Otukpo",
//   "236": "Otukpo CHC",
//   "237": "Otukpo KP OSS",
//   "238": "Oturkpo GH",
//   "239": "Owukpa Basic Health Center",
//   "240": "PHC ACHIA",
//   "241": "PHC Adera",
//   "242": "PHC ADOKA",
//   "243": "PHC Adum-oko",
//   "244": "PHC AJEGBE",
//   "245": "PHC Ajohol",
//   "246": "PHC Akile",
//   "247": "PHC AKPUUNA",
//   "248": "PHC Awuapila",
//   "249": "PHC BOAGUNDU",
//   "250": "PHC Dogo",
//   "251": "PHC Hembafan",
//   "252": "PHC IHUNGWA",
//   "253": "PHC Ikyumbur",
//   "254": "PHC ITAKPA-ITO",
//   "255": "PHC Mbakatu",
//   "256": "PHC Mbandzegh",
//   "257": "PHC Mbashian",
//   "258": "PHC OBA",
//   "259": "PHC OBARIKE",
//   "260": "PHC Ortese Mabaatsua",
//   "261": "PHC Owner Occupier",
//   "262": "PHC Tofi",
//   "263": "PHC UDABILI",
//   "264": "PHC Udei",
//   "265": "PHC Ullam",
//   "266": "PHC Yaikyo",
//   "267": "Phesset Clinic",
//   "268": "Queens Clinic",
//   "269": "Rahama Clinic&Maternity",
//   "270": "Royal Clinic&Maternity Wuese",
//   "271": "Royal Hosp.",
//   "272": "ROYAL SPECIALIST Hosp.",
//   "273": "Sahara Clinic",
//   "274": "Salem Clinic-Gbor",
//   "275": "Salem Hosp.",
//   "276": "Salvation Hosp.",
//   "277": "Sandra Hosp.",
//   "278": "Sankera Family Support Program Clinic",
//   "279": "Sankera GH",
//   "280": "Seafa Clinic&Maternity",
//   "281": "Sev-Av Foundation-Gboko",
//   "282": "Sev-Av Foundation-Otukpo",
//   "283": "Sev-Av Foundation-Vandeikya",
//   "284": "St Elizabeth Hosp.",
//   "285": "St.Anthony's Hosp.-Zaki Biam",
//   "286": "St.Charles' Hosp.",
//   "287": "St.Christopher Clinic-Wannune",
//   "288": "St.Daniel Hosp.",
//   "289": "St.Elizabeth Hosp.",
//   "290": "St.Francis PHC-Agagbe",
//   "291": "St.Gregory Health Center",
//   "292": "St.Joseph Maternity Clinic-Korinya",
//   "293": "St.Joseph's Hosp.-Ogobia",
//   "294": "St.Luke's Hosp.",
//   "295": "St.Martha's Clinic&Maternity-Ugbema",
//   "296": "St.Mary PHC-Chito",
//   "297": "St.Mary's Hosp.-Okpoga",
//   "298": "St.Mary's PHC-Tor Donga",
//   "299": "St.Michaels Clinic",
//   "300": "St.Michael's Clinic-Agasha",
//   "301": "St.Monica's Hosp.-Adikpo",
//   "302": "St.Paul's Clinic-Sambe",
//   "303": "St.Paul's Clinic-Ikyaator",
//   "304": "St.Thomas Hosp.-Ihugh",
//   "305": "St.Veronica Health Center",
//   "306": "St.Vincents Hosp.",
//   "307": "SULAD MEDICAL CENTER",
//   "308": "Tarvachan CHC",
//   "309": "TBT Hosp.-Gboko",
//   "310": "Tiortyu LGA Health Center",
//   "311": "Tongov PHC",
//   "312": "Tordonga PHC",
//   "313": "Tordoo Clinic",
//   "314": "Township Clinic",
//   "315": "Township Clinic-Wannune",
//   "316": "Township CHC",
//   "317": "TSDP Mbatim",
//   "318": "Tse Agberagba GH",
//   "319": "Tse-Agbaragba PHC",
//   "320": "Tse-Akiishi PHC",
//   "321": "Tseghem CHC",
//   "322": "Tse-Tiah PHC",
//   "323": "Tugudu PHC",
//   "324": "Tyoate CHC",
//   "325": "Tyowanye PHC",
//   "326": "Uboagere CHC",
//   "327": "Uga PHC",
//   "328": "Ugba CHC",
//   "329": "Ugba GH",
//   "330": "Ugbokpo GH",
//   "331": "Ukum KP OSS",
//   "332": "Une LGA Health Centre",
//   "333": "Usaka Clinic Tsuwe",
//   "334": "Ushakaa Hosp.",
//   "335": "Ushongo CHC",
//   "336": "Ushongo KP OSS",
//   "337": "Uzer LGA Health Center",
//   "338": "Vaase LGA Health Center",
//   "339": "Vandeikya GH",
//   "340": "Vandeikya KP OSS -Virtual",
//   "341": "Victory Hosp.-Gboko",
//   "342": "Waapera CHC",
//   "343": "Wannune GH",
//   "344": "Wellness Clinic-High level",
//   "345": "Wende PHC",
//   "346": "WHC Agu",
//   "347": "Woma Clinic&Maternity",
//   "348": "World Health System Sai",
//   "349": "Yaakar CHC",
//   "350": "Yima Hosp.",
//   "351": "Zaki-Biam City Clinic&Maternity",
//   "352": "Zamzam PHC",
// };
//
// final Borno = {
//   "1": "Askira GH",
//   "2": "Bama GH",
//   "3": "Biu GH",
//   "4": "bo FHI360 Clinic,Banki IDP Camp",
//   "5": "bo ISS IDP Camp Clinic Ngala",
//   "6": "bo Umaru Shehu Ultra Modern Hosp.",
//   "7": "Briyel GH",
//   "8": "Gwoza GH",
//   "9": "Konduga GH",
//   "10": "Lassa GH",
//   "11": "Maiduguri State Specialist Hosp.",
//   "12": "Monguno GH",
//   "13": "Muhammed Shuwa Memorial Hosp.",
//   "14": "Ngala GH",
//   "15": "University of Maiduguri Teaching Hosp.",
// };
//
// final CrossRiver = {
//   "1": "Adijinkpo PHC",
//   "2": "Akani Esuk Health Centre",
//   "3": "Akpabuyo St Joseph Hosp.",
//   "4": "Akpet Central Cottage Hosp.",
//   "5": "Anantigha PHC",
//   "6": "Anderson PHC",
//   "7": "Angel Clinic",
//   "8": "Aningeje PHC",
//   "9": "Ansor Clinic",
//   "10": "Apiapum Health Centre",
//   "11": "Aya Medical Centre",
//   "12": "Ayughasa Health Post",
//   "13": "Bacoco Health Post",
//   "14": "Bakassi KP OSS- Virtual",
//   "15": "Bakor Hosp.",
//   "16": "Bakor Medical centre",
//   "17": "Biocee Zion Maternity",
//   "18": "Blessed Seaatoe Maternity clinic",
//   "19": "Calabar GH",
//   "20": "Calabar Municipal KP OSS",
//   "21": "Calabar South Family Health Centre",
//   "22": "Calabar Women&Children Hosp.",
//   "23": "CHC Ikom",
//   "24": "cIkot Obong Health Centre",
//   "25": "Country Specialist Hosp.",
//   "26": "cr Akamkpa GH",
//   "27": "cr Ikot Enebong Health Post",
//   "28": "cr Obanliku GH",
//   "29": "CRUTECH Medical Centre",
//   "30": "Dannex Medical Center",
//   "31": "Diamond Hill Health Centre",
//   "32": "Dr Lawrence Henshaw Memorial Hosp.",
//   "33": "Eja Memorial Hosp.",
//   "34": "Ekana Medical Centre",
//   "35": "Ekorinim Health Centre",
//   "36": "Ekpo Abasi PHC",
//   "37": "Ekpri Obutong Health Centre",
//   "38": "Emmanuel Infirmiry",
//   "39": "Essierebom PHC",
//   "40": "Evangel Model Clinic",
//   "41": "Eyo Medical Center",
//   "42": "Faith Foundation Clinic",
//   "43": "Fed Neuropsychiatric Hosp.",
//   "44": "Fountain Clinic",
//   "45": "GH Obudu",
//   "46": "Goldie Clinic",
//   "47": "Henshaw Town Health Post",
//   "48": "Hiltop Healthcare Foundation",
//   "49": "Holy Family Cath. Hosp.",
//   "50": "Ideal Medical Centre",
//   "51": "Idum Health Centre",
//   "52": "Igbo-Imabana Model PHC",
//   "53": "Ikang PHC",
//   "54": "Iko Esai PHC",
//   "55": "Ikom KP OSS- Virtual",
//   "56": "Ikot Edem Odo Health Centre",
//   "57": "Ikot Effiong Otop CHC(UCTH Annex)",
//   "58": "Ikot Ekpo Health Post(Ward 10)",
//   "59": "Ishie Health Post",
//   "60": "Kasuk Health Centre",
//   "61": "Katchuan Irruan Model PHC",
//   "62": "Mambo Clinic",
//   "63": "Melrose Hosp.",
//   "64": "Mfamosing PHC ",
//   "65": "Mission Hill Clinic",
//   "66": "Mma Efa Health Centre",
//   "67": "Mount Zion Medical Centre",
//   "68": "Nyahasang Health Centre",
//   "69": "NYSC Community Health Centre",
//   "70": "Oba CHC",
//   "71": "Oban Cottage Hosp.",
//   "72": "Oban Health Centre",
//   "73": "Obubra GH",
//   "74": "Obubra Maternal&Child Clinic",
//   "75": "Obudu Clinic",
//   "76": "Obudu Urban1 PHC",
//   "77": "Ogoja Cath. Maternity Hosp.",
//   "78": "Ogoja GH",
//   "79": "Ogoja KP OSS- Virtual",
//   "80": "Ogoja Santa Maria Clinic",
//   "81": "Ogurude Health Centre",
//   "82": "Okpoma GH",
//   "83": "Okundi CHC",
//   "84": "Peace medical centre",
//   "85": "PHC  Iffiang King Duke",
//   "86": "PHC Ababene",
//   "87": "PHC Abia",
//   "88": "PHC Abuochiche",
//   "89": "PHC Agwawune",
//   "90": "PHC Ajere",
//   "91": "PHC Akansoko",
//   "92": "PHC Akpap-okoyong",
//   "93": "PHC Akwa Ikot Effanga",
//   "94": "PHC Awi",
//   "95": "PHC Bendeghe",
//   "96": "PHC Creek Town I",
//   "97": "PHC Effraya",
//   "98": "PHC Ekpri Ikot Ene",
//   "99": "PHC Ekumtak",
//   "100": "PHC Emanghebe",
//   "101": "PHC Epenti",
//   "102": "PHC Ibil",
//   "103": "PHC Idundu",
//   "104": "PHC Ikoneto",
//   "105": "PHC Ikot Effanga Mkpa",
//   "106": "PHC Ikot Nakanda",
//   "107": "PHC Ikot Offiong Ambai",
//   "108": "PHC Itigidi",
//   "109": "PHC Iwuru",
//   "110": "PHC Iyamoyong",
//   "111": "PHC Kakwagom",
//   "112": "PHC Mbarakom",
//   "113": "PHC Ntankpo",
//   "114": "PHC Ochong",
//   "115": "PHC Odukapani Qua",
//   "116": "PHC Ofudua",
//   "117": "PHC Okuni",
//   "118": "PHC Olachor",
//   "119": "PHC Old Netim",
//   "120": "PHC Sankwala",
//   "121": "PHC Ugep",
//   "122": "PHC Urua Etak Uyo",
//   "123": "PHC Usung Esuk",
//   "124": "PHC Uyanga",
//   "125": "PHC Wonye",
//   "126": "PHC Wula",
//   "127": "PHC Yenon",
//   "128": "Police Hosp.",
//   "129": "Progress Clinic",
//   "130": "Sacred Heart Cath. Hosp.",
//   "131": "Ugep GH",
//   "132": "Ukpem GH",
//   "133": "University of Calabar Medical Centre",
//   "134": "University of Calabar Teaching Hosp.",
//   "135": "USY Medical Center",
//   "136": "Victoria Itam Specialist Hosp.",
//   "137": "Wanihem CHC",
//   "138": "Yakurr KP OSS- Virtual",
//   "139": "Yala Lutheran Hosp.",
// };
//
// final Delta = {
//   "1": "Abraka GH",
//   "2": "Agbarho PHC -GH",
//   "3": "Agbor Central Hosp.",
//   "4": "Agbor-Aladinma GH",
//   "5": "Akwukwu-Igbo GH",
//   "6": "Ashaka Govt Hosp.",
//   "7": "Assumption Cath. Hosp.-Warri",
//   "8": "Bomadi GH",
//   "9": "Brema Hosp.-Kwale",
//   "10": "de Aniocha North",
//   "11": "de Aniocha South",
//   "12": "de Bomadi",
//   "13": "de Burutu",
//   "14": "de Ethiope East",
//   "15": "de Ethiope West",
//   "16": "de Ika North East",
//   "17": "de Ika South",
//   "18": "de Isoko North",
//   "19": "de Isoko South",
//   "20": "de Ndokwa East",
//   "21": "de Ndokwa West",
//   "22": "de Okpe",
//   "23": "de Oshimili North",
//   "24": "de Oshimili South",
//   "25": "de Patani",
//   "26": "de Sapele",
//   "27": "de Sapele Central Hosp.",
//   "28": "de Udu",
//   "29": "de Ughelli North",
//   "30": "de Ughelli South",
//   "31": "de Ukwuani",
//   "32": "de Uvwie",
//   "33": "de Warri Central Hosp.",
//   "34": "de Warri North",
//   "35": "de Warri South",
//   "36": "de Warri South-West",
//   "37": "Delta State UNTHosp",
//   "38": "Ebu GH",
//   "39": "Ekpan GH",
//   "40": "Eku Govt Hosp.",
//   "41": "Erhoike Cottage Hosp.",
//   "42": "FMC-Asaba",
//   "43": "Ibusa GH",
//   "44": "Isheagu GH",
//   "45": "Issele-Ukwu GH",
//   "46": "Koko GH",
//   "47": "KPIF_Ika South OSS",
//   "48": "KPIF_Oshimili South OSS",
//   "49": "KPIF_Udu OSS",
//   "50": "KPIF_Ughelli North OSS",
//   "51": "KPIF_Warri South OSS",
//   "52": "Kwale Central Hosp.",
//   "53": "Obiaruku GH",
//   "54": "Oghara GH",
//   "55": "Ogwashi-uku GH",
//   "56": "Okwe GH",
//   "57": "Oleh Central Hosp.",
//   "58": "Onicha-Olona GH",
//   "59": "Orerokpe GH",
//   "60": "Otor Udu GH",
//   "61": "Otu-Jeremi GH",
//   "62": "Our Lady of Nigeria Clinic-Oghara",
//   "63": "Our Lady of Waters",
//   "64": "Owa-Alero GH",
//   "65": "Owhelogbo Govt Hosp.",
//   "66": "Ozoro GH",
//   "67": "Patani GH",
//   "68": "PHC Tahatihi",
//   "69": "PHC Zor",
//   "70": "Sage Clinic",
//   "71": "St.&rews Hosp.&Maternity",
//   "72": "St.Francis Cath. Hosp.-Okpara Inland",
//   "73": "St.Joseph's Hosp.-Asaba",
//   "74": "St.Mary's Clinic&Maternity-Ozoro",
//   "75": "St.Rebecca Clinic",
//   "76": "St.Theresa's Cath. Hosp.-Issele Uku",
//   "77": "Tse kpum",
//   "78": "TB Referral Center-Eku",
//   "79": "Ughelli Central Hosp.",
//   "80": "Umunede GH",
//   "81": "Umutu Govt Hosp.",
//   "82": "Uzere Cottage Hosp.",
// };
//
// final Ebonyi = {
//   "1": "Abina Health Center",
//   "2": "Afikpo Medical Center",
//   "3": "Afikpo Medical Center",
//   "4": "Ebonyi State OSS(OSS),Abakaliki",
//   "5": "Elinwovbu GH",
//   "8": "Ezzangbo GH",
//   "9": "Federal Teaching Hosp.(FETHA)-Abakaliki",
//   "11": "Iboko GH",
//   "12": "Ikwo GH",
//   "14": "Ishiagu GH",
//   "16": "Life Care Clinic",
//   "18": "Little Seed Hosp.",
//   "20": "Maria Ines Hosp.-Ezillo",
//   "22": "Mater Misericordiae Hosp.-Afikpo",
//   "24": "Mercy Hosp.&Maternity",
//   "26": "Okposi GH",
//   "28": "Onicha GH",
//   "29": "Onueke GH",
//   "31": "Owutu GH",
//   "33": "Police Clinic-Abakaliki",
//   "36": "Romec Hosp.&Maternity",
//   "37": "Rural Improvement Hosp.-Ikwo",
//   "39": "St.Charles Clinic",
//   "41": "St.Patrick Mile 4 Hosp.-Abakaliki",
//   "43": "St.Vincent Hosp.-Ndubia",
//   "45": "St.Vincent Hosp.,Amudo",
//   "46": "Sudan United Mission Hosp.-Effium",
//   "49": "Sudan United Mission Hosp.-Iboko",
//   "50": "Sudan United Mission Hosp.-Onuenyim",
//   "52": "Uburu Presbyterian Joint Hosp.",
// };
//
// final Edo = {
//   "1": "Abudu GH",
//   "2": "Afuze Referral Medical Centre",
//   "3": "Agenebode GH",
//   "4": "Alafia Specialist Hosp.",
//   "5": "Auchi Central Hosp.",
//   "6": "Benin Evangel Model Hosp.",
//   "7": "Ebelle PHC",
//   "8": "ed Benin Central Hosp.",
//   "9": "Edo State OSS(OSS),Benin",
//   "10": "Ekpoma GH",
//   "11": "Evubtubu PHC",
//   "12": "Faith Mediplex",
//   "13": "Ibillo GH",
//   "14": "Igarra GH",
//   "15": "Igueben PHC",
//   "16": "Iguobazua GH",
//   "17": "Ikueniro PHC",
//   "18": "Irrua Specialist Hosp.",
//   "19": "Iruekpen GH",
//   "20": "Oben Cottage Hosp.",
//   "21": "Okugbe PHC",
//   "22": "Oriaifo Medical Centre",
//   "23": "Ossiomio Specialist Hosp.",
//   "24": "Sabongida Ora GH",
//   "25": "Santa Maria Cath. Hosp.",
//   "26": "St.Philomena Cath. Hosp.",
//   "27": "St.Camillus Hosp.",
//   "28": "St.Camillus Hosp.",
//   "29": "Stella Obasanjo Women&Children Hosp.",
//   "30": "Ubiaja GH",
//   "31": "Udo PHC",
//   "32": "University of Benin Teaching Hosp.(UBTH)",
//   "33": "Uromi Central Hosp.",
//   "34": "Usen GH",
//   "35": "Uzebba GH",
// };
//
// final Ekiti = {
//   "1": "Aramoko Ekiti GH",
//   "2": "ek Ado-Ekiti",
//   "3": "ek Efon",
//   "4": "ek Ekiti East",
//   "5": "ek Ekiti South-West",
//   "6": "ek Ekiti West",
//   "7": "ek Emure",
//   "8": "ek Gbonyin",
//   "9": "ek Ido-Osi",
//   "10": "ek Ijero",
//   "11": "ek Ikere",
//   "12": "ek Ikole",
//   "13": "ek Ilejemeje",
//   "14": "ek Irepodun-Ifelodun",
//   "15": "ek Ise-Orun",
//   "16": "ek Moba",
//   "17": "ek Oye",
//   "18": "Ekiti State UNTHosp,Ado-Ekiti",
//   "19": "Emure Ekiti GH",
//   "20": "FMC,Ido-Ekiti",
//   "21": "Ifaki Ekiti GH",
//   "22": "Ijero Ekiti State Specialist Hosp.",
//   "23": "Ikere Ekiti State Specialist Hosp.",
//   "24": "Ikole-Ekiti State Hosp.",
//   "25": "Ilawe Ekiti CHC",
//   "26": "Iye Ekiti GH",
//   "27": "Iyin Ekiti GH",
//   "28": "Okesa Ekiti CHC",
//   "29": "Omuo Ekiti GH",
//   "30": "Oye Ekiti GH",
//   "31": "St.Gregory Hosp. Ado-Ekiti",
// };
//
// final Enugu = {
//   "1": "Achi Joint Hosp.",
//   "2": "Annunciation Specialist Hosp.- Emene",
//   "3": "Asata Poly Clinic(Sub District Hosp.)",
//   "4": "Attah Memorial Hosp.",
//   "5": "Awgu District Hosp.",
//   "6": "Awgu Maternal&Child Clinic",
//   "7": "Balm of Gilead Hosp.",
//   "8": "Chima Hosp.&Maternity",
//   "9": "Daughters of Divine Love-Ehalumona",
//   "10": "Divine Grace Hosp.",
//   "11": "Elechi Medical Clinic-Ukehe",
//   "12": "en Agbani District Hosp.,Agbani",
//   "13": "en Aninri",
//   "14": "en Awgu",
//   "15": "en Bishop Shanahan Hosp.,Nsukka",
//   "16": "en Enugu East",
//   "17": "en Enugu North",
//   "18": "en Enugu South",
//   "19": "en Enugu State OSS(OSS),Enugu",
//   "20": "en Ezeagu",
//   "21": "en Igbo Etiti",
//   "22": "en Igbo Eze North",
//   "23": "en Igbo Eze South",
//   "24": "en isi uzo",
//   "25": "en Nkanu East",
//   "26": "en Nkanu West",
//   "27": "en Nsukka",
//   "28": "en Oji River",
//   "29": "en Udenu",
//   "30": "en Udi",
//   "31": "en Uzo Uwani",
//   "32": "Enugu Eastern Medical Hosp.",
//   "33": "Enugu State OSS(OSS),Enugu",
//   "34": "Enugu State UNTHosp",
//   "35": "Enugu-Ezike District Hosp.",
//   "36": "Faith Foundation Mission Hosp.-Nsukka",
//   "37": "Iji Nike Cottage Hosp.",
//   "38": "Ikem District Hosp.",
//   "39": "Mother of Christ Specialist Hosp.",
//   "40": "Mother of Mercy Hosp.-Ihe",
//   "41": "Nsude Health Center",
//   "42": "Nsukka District Hosp.",
//   "43": "Nsukka Health Center",
//   "44": "Ntasi-Obi Hosp.,Enugu",
//   "45": "Nussy Sadiq Memorial Hosp.-Nsukka",
//   "46": "Obollo Affor Health Center",
//   "47": "Oji River Sub District GH",
//   "48": "Our Lady Health of the Sick Hosp.,Adani",
//   "49": "Our Lady's Clinic",
//   "50": "Our Saviour Hosp.&Maternity",
//   "51": "Royal Hosp.,Iva-ValleyEnugu",
//   "52": "St.Mary Hosp.",
//   "53": "The Good Shepherd Hosp.-Uwani",
//   "54": "Udi District Hosp.",
//   "55": "University Of Nigeria Teaching Hosp",
//   "56": "Uwani Cottage Hosp.",
// };
//
// final FCT = {
//   "1": "360 Care Clinic&Maternity,Mpape",
//   "2": "Abaji GH",
//   "3": "Abuja Clinic",
//   "4": "Access Clinic",
//   "5": "Agwandodo",
//   "6": "Alheri Kuntuku Clinic",
//   "7": "Allison Medical Centre",
//   "8": "Anawim OSS",
//   "9": "Apo PHC",
//   "10": "Asokoro District Hosp.",
//   "11": "Ayaura CHC",
//   "12": "Azriel Hosptial Lugbe",
//   "13": "Bethel Clinic&Maternity",
//   "14": "Bwari GH",
//   "15": "Bwari Medical Center",
//   "16": "Byazhin PHC",
//   "17": "Cornelia Hosp.",
//   "18": "Cornelian Maternity&Rural Health",
//   "19": "Cream Medics",
//   "20": "Custom Staff Clinic",
//   "21": "Dabibako PHC",
//   "22": "Dagiri PHC",
//   "23": "Daughters of Charity(DOC) Hosp.-Kubwa",
//   "24": "Dei Dei CHC",
//   "25": "Diamond Crest Hosp.&Maternity",
//   "26": "Diamond Medical Center",
//   "27": "Dominion Hosp.",
//   "28": "Dutse Alhaji PHC",
//   "29": "Dutsen Garki PHC",
//   "30": "ECWA Clinic-Kabusa",
//   "31": "ECWA Medical Center",
//   "32": "(EFMC) Care Center(Modern Health Hosp.)",
//   "33": "Faith Medical Center-Karimo",
//   "34": "fc Abaji",
//   "35": "fc AMAC",
//   "36": "fc Bwari",
//   "37": "fc Gwags",
//   "38": "fc Kuje",
//   "39": "fc Kwali",
//   "40": "fc St Mary Cath. Hosp.,Gwags",
//   "41": "fc Wuse District Hosp.",
//   "42": "Federal Road Safety Hosp.",
//   "43": "Federal Staff Hosp.-Gwarimpa",
//   "44": "Federal Staff Hosp.-Jabi",
//   "45": "Freedomscan Medical Center",
//   "46": "Gabic Divine Clinic&Maternity",
//   "47": "Garki Hosp. Abuja",
//   "48": "Gaube CHC",
//   "49": "Getwell Hosp.",
//   "50": "GH Kuje",
//   "51": "GH Robochi",
//   "52": "Gidan Mangoro PHC",
//   "53": "Goodness Land Clinic&Maternity",
//   "54": "Gwagwa PHC",
//   "55": "Gwags Clinic&Maternity",
//   "56": "Gwags KP OSS",
//   "57": "Gwags Township Clinic",
//   "58": "Gwarimpa GH",
//   "59": "Gwarinpa OSS",
//   "60": "Iddo Pada PHC",
//   "61": "Idu Karimo PHC",
//   "62": "International Center for Advocacy",
//   "63": "Jahi PHC",
//   "64": "Jerab Hosp.s",
//   "65": "Jikwoyi Medical Center",
//   "66": "Jikwoyi PHC",
//   "67": "Joefag Alheri Clinic&Maternity",
//   "68": "Kabusa PHC",
//   "69": "Kagini PHC",
//   "70": "Karshi GH",
//   "71": "Karu PHC",
//   "72": "King's Care Hosp.",
//   "73": "Kogo PHC",
//   "74": "Kpaduma PHC",
//   "75": "KPIF_Gwarinpa OSS",
//   "76": "Kubwa GH",
//   "77": "Kuchingoro PHC",
//   "78": "Kuje PHC",
//   "79": "Kwali GH",
//   "80": "Laura Hosp.&Maternity",
//   "81": "Living Rock Hosp.&Maternity",
//   "82": "Lugbe PHC",
//   "83": "MABUSHI OSS",
//   "84": "Maitama GH",
//   "85": "Massan Clinic Limited",
//   "86": "M-Dali Hosp.",
//   "87": "Medical Missions of Mary-Lugbe",
//   "88": "Minat Clinic",
//   "89": "Mpape PHC",
//   "90": "National Hosp.-Abuja",
//   "91": "National Institute For Pharm Research-Idu",
//   "92": "Nyanya GH",
//   "93": "Nyanya OSS",
//   "94": "Old Kutunku",
//   "95": "Omega Hosp.",
//   "96": "Our Lady of Fatima Hosp.-Bwari",
//   "97": "Pan-Raf Hosp.",
//   "98": "PHC Abattoir",
//   "99": "PHC Ayeleta",
//   "100": "PHC BAKO",
//   "101": "PHC Dakwa",
//   "102": "PHC Dobi",
//   "103": "PHC Gosa",
//   "104": "PHC IJAR SARKI",
//   "105": "PHC Kiyi",
//   "106": "PHC Kpeyegi",
//   "107": "PHC Kuchiyako",
//   "108": "PHC Tunga Maje",
//   "109": "PHC Waru",
//   "110": "Pigba Medical Center",
//   "111": "Police Clinic-Abuja",
//   "112": "Rainbow Hosp.&Maternity",
//   "113": "Rapha Hosp.",
//   "114": "Rhema Hosp. Kwali",
//   "115": "Ruz Medical&Diag. Centre",
//   "116": "Sabon Gari PHC",
//   "117": "Sisters of Nativity Hosp.(SON)-Jikwoyi",
//   "118": "St.&rews Anglican Hosp.-Kubwa",
//   "119": "Standard Care Hosp.",
//   "120": "State House Clinic",
//   "121": "Sumit Hosp.",
//   "122": "The Crown Hosp.",
//   "123": "Unity Clinic&Maternity",
//   "124": "University Of Abuja Teaching Hosp.-Gwagwalda",
//   "125": "Welness clinic- abuja",
//   "126": "Yabisam Hosp.",
//   "127": "YOUTHRISE OSS",
//   "128": "Zuba PHC",
// };
//
// final Gombe = {
//   "1": "Ashaka Cement Clinic",
//   "2": "Bajoga GH",
//   "3": "Bam Bam Cottage Hosp.",
//   "4": "Billiri GH",
//   "5": "Bojude Cottage Hosp.",
//   "6": "Deba GH",
//   "7": "Doma Hosp.",
//   "8": "Dukku GH",
//   "9": "FMC-Gombe",
//   "10": "Filiya PHC",
//   "11": "go Akko",
//   "12": "go Balanga",
//   "13": "go Billiri",
//   "14": "go Dukku",
//   "15": "go Funakaye",
//   "16": "go Gombe",
//   "17": "go Kaltungo",
//   "18": "go Kumo GH",
//   "19": "go Kwami",
//   "20": "go Nafada",
//   "21": "go Nafada-Bajoga",
//   "22": "go Shongom",
//   "23": "go Yamaltu/Deba",
//   "24": "Gombe State OSS(OSS),Bajoga",
//   "25": "Gombe State Specialist Hosp.",
//   "26": "Iliya Nursing Home&Maternity",
//   "27": "Infectious Disesase Hosp.-Zambuk",
//   "28": "Kaltungo GH",
//   "29": "Kashere GH",
//   "30": "Madi Memorial Clinic&Maternity",
//   "31": "Miyetti Hosp.",
//   "32": "Musaba Clinic",
//   "33": "Nafada GH",
//   "34": "Sabana Specialist Hosp.",
//   "35": "Talase GH",
//   "36": "Tula Cottage Hosp.",
//   "37": "Yambu Dok Clinic",
// };
//
// final Imo = {
//   "1": "Abba 1 PHC-Umuopara",
//   "2": "Aboh Mbaise GH",
//   "3": "Akabo Health Center",
//   "4": "Akwakuma Health Center",
//   "5": "Awo Omamma GH",
//   "6": "Chiwendu Hosp. Awo Omama",
//   "7": "Chokoneze Ndutu PHC",
//   "8": "Ebenato Ekwe Health Center",
//   "9": "Ebenator Health Center",
//   "10": "Elelem PHC",
//   "11": "FMC-Owerri",
//   "12": "GH Egbema",
//   "13": "Holy Rosary Hosp.-Emekuku",
//   "14": "Holy Rosary Hosp. Ogbor Nguru",
//   "15": "Ihitte-Ogada Health Center",
//   "16": "Iho Basic Health Center",
//   "17": "im Aboh Mbaise",
//   "18": "im Ahiazu Mbaise",
//   "19": "im Ehime Mbano",
//   "20": "im Ezinihitte",
//   "21": "im Ezinihitte",
//   "22": "im Ideato North",
//   "23": "im Ideato South",
//   "24": "im Ihitte/Uboma",
//   "25": "im Ikeduru",
//   "26": "im Imo Specialist Hosp.,Owerri",
//   "27": "im Imo State OSS(OSS),Owerri",
//   "28": "im Isiala Mbano",
//   "29": "im Isu",
//   "30": "im Mbaitoli",
//   "31": "im Mbano Joint Hosp.",
//   "32": "im Ngor Okpala",
//   "33": "im Ngor Okpala",
//   "34": "im Njaba",
//   "35": "im Nkwerre",
//   "36": "im Nwangele",
//   "37": "im Obowo",
//   "38": "im Oguta",
//   "39": "im Ohaji/Egbema",
//   "40": "im Okigwe",
//   "41": "im Orlu",
//   "42": "im Orsu",
//   "43": "im Oru East",
//   "44": "im Oru West",
//   "45": "im Owerri Municipal",
//   "46": "im Owerri North",
//   "47": "im Owerri West",
//   "48": "im St.Damian Cath. Hosp.,Orlu",
//   "49": "im Unuimo",
//   "50": "Immaculate Hosp.-Urualla",
//   "51": "Imo State OSS(OSS),Owerri",
//   "52": "Imo State UNTHosp",
//   "53": "Mbieri GH",
//   "54": "Naze Health Center",
//   "55": "Ndukwu Hosp.",
//   "56": "Ngor Okpala GH",
//   "57": "Nworieubi PHC",
//   "58": "Ogwa GH",
//   "59": "Okigwe GH",
//   "60": "Osina Community Hosp.",
//   "61": "Our Lady of Mercy-Obowo",
//   "62": "Owerre Nkworji Health Center",
//   "63": "St.Mary Joint Hosp.-Amaigbo",
//   "64": "Umuezeala Owere Health Center",
// };
//
// final Jigawa = {
//   "1": "Babura GH",
//   "2": "Bamaina PHC",
//   "3": "Birnin-Kudu FMC",
//   "4": "Birniwa GH",
//   "5": "Dutse GH",
//   "6": "Gawuna PHC",
//   "7": "Gwaram Cottage Hosp.",
//   "8": "Gwaram PHC",
//   "9": "Gwiwa Model PHC",
//   "10": "Hadejia GH",
//   "11": "Jahun GH",
//   "12": "jBirnin Kudu GH",
//   "13": "jg Gumel GH",
//   "14": "Kafin Hausa GH",
//   "15": "Kazaure GH",
//   "16": "Kofar Arewa PHC",
//   "17": "Rasheed Shekoni Specialist Hosp.",
//   "18": "Ringim GH",
//   "19": "Taura PHC",
// };
//
// final Kaduna = {
//   "1": "Ahmadu Bello UNTHosp",
//   "2": "Amina Hosp.",
//   "3": "Anna-Kitcher Hosp.",
//   "4": "Badarawa PHC",
//   "5": "Barau Dikko Specialist Hosp.",
//   "6": "Barnawa PHC",
//   "7": "Doka Rural Hosp.",
//   "8": "FOMWAN Hosp.",
//   "9": "Foltz Medical Center",
//   "10": "Giwa GH",
//   "11": "Gwamna Awan GH",
//   "12": "Gwantu GH",
//   "13": "Hajiya Gambo Sawaba Hosp.",
//   "14": "Harmony Hosp.",
//   "15": "Harmony Hosp.",
//   "16": "Hunkuyi GH",
//   "17": "Idon Rural Hosp.",
//   "18": "Jaji CHC",
//   "19": "Jibrin Maigwari GH",
//   "20": "Jowako Hosp.",
//   "21": "Kachia GH",
//   "22": "Kaduna State OSS",
//   "23": "Kafanchan Family Health Unit",
//   "24": "Kafanchan GH",
//   "25": "Kagarko GH",
//   "26": "Kaura Rural Hosp.",
//   "27": "Kauru Rural Hosp.",
//   "28": "Kawo GH",
//   "29": "kd Birnin Gwari",
//   "30": "kd Chikun",
//   "31": "kd Giwa",
//   "32": "kd Giwa Hosp.",
//   "33": "kd Igabi",
//   "34": "kd Ikara",
//   "35": "kd Ikara GH",
//   "36": "kd Jaba",
//   "37": "kd Jema",
//   "38": "kd Kachia",
//   "39": "kd Kaduna North",
//   "40": "kd Kaduna South",
//   "42": "kd Kagarko",
//   "43": "kd Kajuru",
//   "44": "kd Kaura",
//   "45": "kd Kauru",
//   "46": "kd Kubau",
//   "47": "kd Kudan",
//   "48": "kd Lere",
//   "49": "kd Makarfi",
//   "50": "kd Rigasa GH",
//   "51": "kd Sabon Gari",
//   "52": "kd Salamat Hosp.",
//   "53": "kd Sanga",
//   "54": "kd Soba",
//   "55": "kd St.Lukes Hosp. Wusasa",
//   "56": "kd Zangon Kataf",
//   "57": "kd Zaria",
//   "58": "Kujama Rural Hosp.",
//   "59": "Kwoi GH",
//   "60": "Maigana GH",
//   "61": "Major Ibrahim Bello Hosp.",
//   "62": "Makarfi GH",
//   "63": "Makera I PHC",
//   "64": "Manchok Maternal&Child Clinic",
//   "65": "Maneks Hosp.",
//   "66": "Muslim Specialist Hosp.",
//   "67": "National TB&Leprosy Center",
//   "68": "Pambegua GH",
//   "69": "Police Medical Center",
//   "70": "Sabo Tsaha PHC",
//   "71": "Sabon Tasha GH",
//   "72": "Saminaka GH",
//   "73": "Sefa Hosp.",
//   "74": "St.Gerald's Hosp.-KD",
//   "75": "St.Louis Hosp.-Zonkwa",
//   "76": "Turaki Buga Memorial Hosp.",
//   "77": "Turunku Rural Hosp.",
//   "78": "Yusuf Dantsoho Memorial Hosp.",
//   "79": "Zakari Isah Memorial Clinic",
//   "80": "Zango-Kataf GH",
//   "81": "Zonkwa Regional Hosp.",
// };
//
// final Kano = {
//   "1": "Ahmadiyya Muslim Hosp.",
//   "2": "Ahmadiyya Muslim Hosp.",
//   "3": "Akilu Memorial Hosp.",
//   "4": "Al-Noury Specialist Hosp.",
//   "5": "Aminu Kano Teaching Hosp.-Kano",
//   "6": "Bebeji GH",
//   "7": "CHC Karaye",
//   "8": "CHC Kiru",
//   "9": "CHC Kumbotso",
//   "10": "CHC Tsanyawa",
//   "11": "Danbatta GH",
//   "12": "Dawakin Kudu GH",
//   "13": "Dawakin Tofa GH",
//   "14": "Doguwa GH",
//   "15": "ECWA Clinic&Maternity",
//   "17": "Gaya GH",
//   "18": "GH Bichi",
//   "19": "GH Gezawa",
//   "20": "GH Tiga",
//   "21": "GH Tudun Wada",
//   "22": "Gwarzo GH",
//   "23": "Hasiya Bayero Paediatric Hosp.",
//   "24": "International Clinic",
//   "25": "Kano Infectious Diseases Hosp.",
//   "26": "Kano State OSS(OSS),Nasarawa",
//   "27": "Khadijat Memorial Hosp.(FGE)",
//   "28": "Kibiya PHC",
//   "29": "Sir Muhammad Sanusi Specialist Hosp.",
//   "30": "kn Wudil GH",
//   "31": "Kura GH",
//   "32": "MCH Dala",
//   "33": "Mohammed Abdullahi Wase Hosp.",
//   "34": "Murtala Mohammed Specialist Hosp.",
//   "35": "Nuhu Bamalli Maternity Hosp.",
//   "36": "PHC Mariya Sanusi",
//   "37": "Rano GH",
//   "38": "Rijiyar Lemo Maternal Child Health",
//   "39": "Rogo GH",
//   "40": "Sheikh Mohammed Jidda GH",
//   "41": "Sumaila GH",
//   "42": "Takai CHC",
//   "43": "Tofa CHC",
//   "44": "Unguwa Uku Maternal&Child Health Centre",
//   "45": "Waziri Shehu Gidado GH",
//   "46": "Zakirai PHC",
// };
//
// final Katsina = {
//   "1": "(A.J.S.) Out Patient Clinic",
//   "2": "Alheri Clinic",
//   "3": "Batsari GH",
//   "4": "Baure GH",
//   "5": "Danmusa GH",
//   "6": "FMC-Katsina",
//   "7": "Funtua GH",
//   "8": "Ingawa GH",
//   "9": "Jibia GH",
//   "10": "Kankara GH",
//   "11": "Kankia GH",
//   "12": "Katsina GH",
//   "13": "kt Daura GH",
//   "14": "kt Dutsinma GH",
//   "15": "Malumfashi GH",
//   "16": "Malumfashi Maternal&Child Clinic",
//   "17": "Mani GH",
//   "18": "Musawa GH",
//   "19": "Rimi GH",
// };
//
// final Kebbi = {
//   "1": "Bunza G.Hosp.",
//   "2": "FMC",
//   "3": "G. Hosp. Aliero",
//   "4": "G.Hosp.",
//   "5": "G.Hosp. Arg.",
//   "6": "G.Hosp. Wara",
//   "7": "GH Yauri",
//   "8": "GH Zauro",
//   "9": "Jega",
//   "10": "Kamba GH",
//   "11": "Kaoje GH",
//   "12": "ke Martha Bamaiyi GH",
//   "13": "Senchi G. Hosp.",
//   "14": "Sir Yahaya Memorial Hosp.",
//   "15": "Wasagu GH",
// };
//
// final Kogi = {
//   "1": "Abejukolo GH",
//   "2": "Aiyetoro Gbede GH",
//   "3": "Ajaokuta Steel Medical Clinic",
//   "4": "Ankpa GH",
//   "5": "Banwo Clinic Iyara",
//   "6": "CHC Ajaka",
//   "7": "CHC Alloma",
//   "8": "CHC Iyara",
//   "9": "Corner Stone Hosp.",
//   "10": "Dekina GH",
//   "11": "ECWA Hosp.,Egbe",
//   "12": "Egume GH",
//   "13": "FAREC Clinic",
//   "14": "FISAYO Clinic",
//   "15": "Gegu Beki PHC",
//   "16": "GH Ifeolukotun",
//   "17": "GH Isanlu",
//   "18": "GH Iyamoye",
//   "19": "GH Mopa",
//   "20": "GH Odo Ere",
//   "21": "Grimmard Hosp.-Anyingba",
//   "22": "Holley Memorial-Ochadamu",
//   "23": "Idah GH",
//   "24": "Ika Christian Hosp.",
//   "25": "Immanuel Clinic",
//   "26": "Iyale GH",
//   "27": "Kabba GH",
//   "28": "ko Adavi",
//   "29": "ko Ajaokuta",
//   "30": "ko Ankpa",
//   "31": "ko Bassa",
//   "32": "ko Dekina",
//   "33": "ko Ibaji",
//   "34": "ko Idah",
//   "35": "ko Igalamela Odolu ",
//   "36": "ko Ijumu",
//   "37": "ko Kabba/Bunu",
//   "38": "ko Kogi",
//   "39": "ko Lokoja",
//   "40": "ko Mopa Muro",
//   "41": "ko Ofu",
//   "42": "ko Ogori/Magongo",
//   "43": "ko Okehi",
//   "44": "ko Okene",
//   "45": "ko Olamaboro",
//   "46": "ko Omala",
//   "47": "ko Yagba East",
//   "48": "ko Yagba West",
//   "49": "Kogi Diagnosis Referral Hosp.",
//   "50": "Kogi State Specialist Hosp.",
//   "51": "Koton-Karfe GH",
//   "52": "KPIF_Adavi OSS",
//   "53": "KPIF_Dekina OSS",
//   "54": "KPIF_LOKOJA OSS",
//   "55": "Lokoja FMC",
//   "56": "Maria Goretti Hosp.",
//   "57": "Nagazi CHC",
//   "58": "Obangede GH",
//   "59": "Ogori GH",
//   "60": "Oguma GH",
//   "61": "Oguma GH",
//   "62": "Okene GH",
//   "63": "Okengwe GH",
//   "64": "Okpo GH",
//   "65": "Rehoboth Specialist Hosp.",
//   "66": "Shukurah Hosp.",
//   "67": "St John's Hosp. Kabba",
//   "68": "Ugwolawo GH",
// };
//
// final Kwara = {
//   "1": "Adewole Cottage",
//   "2": "Aishat Memorial Hosp.",
//   "3": "Ajikobi Cottage Hosp.",
//   "4": "Children Specialist Hosp. C Igboro",
//   "5": "Civil Services Hosp.s",
//   "6": "Erin Ile GH",
//   "7": "Gen. Hosp. Omu-Aran",
//   "8": "General Hosp. Patigi",
//   "9": "GH Lafiagi ",
//   "10": "Jebba State Specialist Hosp.",
//   "11": "Kaiama GH",
//   "12": "kw Ilorin GH",
//   "13": "Kwara State OSS(OSS),Ilorin",
//   "14": "Okelele Health Centre",
//   "15": "Olanrewaju Hosp.",
//   "16": "Olufadi Basic Health Center",
//   "17": "Pakata Health Centre.",
//   "18": "Sabo Oke Medical Centre",
//   "19": "Sadiku Hosp.",
//   "20": "Shonga CHC",
//   "21": "Specialist Hosp. Offa",
//   "22": "Specialist Hosp. Sobi",
//   "23": "Surulere Medical Centre",
//   "24": "Temitope Hosp.",
//   "25": "University of Ilorin Teaching Hosp.",
// };
//
// final Lagos = {
//   "1": "A Harmony Hosp.",
//   "2": "Abule-Nla PHC",
//   "3": "Adams Hosp.",
//   "4": "Agbado Kola PHC",
//   "5": "Agboju PHC",
//   "6": "Agege KP OSS",
//   "7": "Ahamadiyya Muslim Hosp.",
//   "8": "Ajah PHC",
//   "9": "Ajara PHC",
//   "10": "Ajeabo PHC",
//   "11": "Ajeromi GH",
//   "12": "Ajido PHC",
//   "13": "Akere PHC",
//   "14": "Akerela PHC",
//   "15": "Akoka PHC",
//   "16": "Akonwonjo PHC",
//   "17": "Alimosho GH",
//   "18": "All Souls Hosp.",
//   "19": "Amukoko PHC",
//   "20": "Amuwo Odofin KP OSS",
//   "21": "Ancilla Cath. Hosp.",
//   "22": "Apa PHC",
//   "23": "Apapa GH",
//   "24": "Apapa Specialist Hosp.",
//   "25": "Aregbesola PHC",
//   "26": "Ashogbon PHC",
//   "27": "Ayantuga PHC",
//   "28": "Badagry GH",
//   "29": "Badagry KP OSS- Virtual",
//   "30": "Badore PHC",
//   "31": "Baruwa PHC",
//   "32": "Broad Hosp.",
//   "33": "Christ the King Cath. Hosp.-Akowonjo",
//   "34": "Coker Aguda PHC",
//   "35": "Dako Medical Centre Limited",
//   "36": "Deetab Hosp.",
//   "37": "Dopemu PHC",
//   "38": "DUNIA Hosp.",
//   "39": "Ejire PHC",
//   "40": "Era Mini PHC",
//   "41": "Eti-Osa KP OSS",
//   "42": "Faleti Medical Centre",
//   "43": "Falomo Police Hosp.",
//   "44": "Folabi Medical Centre",
//   "45": "Gbagada GH",
//   "46": "GH Agbowa",
//   "47": "GH Epe",
//   "48": "GH Ijede",
//   "49": "GH Ikorodu",
//   "50": "GH Isolo",
//   "51": "Gowon Estate Hosp.-Ipaja",
//   "52": "Harvey Road CHC",
//   "53": "Holy Family Hosp._Lagos",
//   "54": "Iba PHC",
//   "55": "Ibafon PHC",
//   "56": "Ibeju-Lekki GH",
//   "57": "Iduna Specialist Hosp.",
//   "58": "Ifako Ijaiye GH",
//   "59": "Ifako PHC",
//   "60": "Ifunaya Hosp.",
//   "61": "Iga Idugaran PHC",
//   "62": "Ijanikin PHC",
//   "63": "Ijora PHC",
//   "64": "Ikate PHC",
//   "65": "Ikorodu KP OSS",
//   "66": "Ikotun PHC",
//   "67": "Ilado PHC",
//   "68": "Iloro PHC",
//   "69": "Ipaja PHC",
//   "70": "Iru PHC",
//   "71": "Iwaya PHC",
//   "72": "Jim Sam Hosp.&Maternity",
//   "73": "Jordan Hosp.",
//   "74": "Ladilak Medical Centre",
//   "75": "Lagos GH",
//   "76": "Lagos Island Maternity Hosp.",
//   "77": "Lagos Island OSS- Virtual",
//   "78": "Lagos State Mainland Hosp.",
//   "79": "Lagos State UNTHosp",
//   "80": "Lagos UNTHosp(LUTH)",
//   "81": "Layeni PHC",
//   "82": "lKetu PHC",
//   "83": "LONGE MEDICAL Center",
//   "84": "Mafowoku PHC",
//   "85": "Marina PHC",
//   "86": "Mary the Queen Hosp.-Akowonjo",
//   "87": "Massey Street Childrens Hosp.",
//   "88": "MAYFAIR Medical Centre",
//   "89": "Meiran PHC",
//   "90": "Mobonike Hosp.",
//   "91": "Mother Theresa Medical Center-Idimu",
//   "92": "Mowo PHC",
//   "93": "Mushin GH",
//   "94": "Mushin KP OSS",
//   "95": "Natafod Consultants Hosp.",
//   "96": "Nigerian Institute of Medical Research",
//   "97": "Oba Adeyinka Oyekan PHC",
//   "98": "Oba Salami PHC",
//   "99": "Odunbaku PHC",
//   "100": "Ojo KP OSS- Virtual",
//   "101": "Ojo PHC",
//   "102": "Ojodu PHC",
//   "103": "Olive Medicare Hosp.",
//   "104": "Olojowon PHC",
//   "105": "Oluwole PHC",
//   "106": "Ondo West PHC",
//   "107": "Onikan Health Centre",
//   "108": "Orile Agege GH",
//   "109": "Oyem's Hosp.",
//   "110": "Palm Avenue PHC",
//   "111": "Papa Uku PHC",
//   "112": "Patol Medical Centre",
//   "113": "Pota PHC",
//   "114": "Powerline PHC",
//   "115": "Prince&Princess Hosp.",
//   "116": "Promise Medical Centre",
//   "117": "R Jolad Hosp.",
//   "118": "Randle GH",
//   "119": "Redeemed Aid Programme Action Committee",
//   "120": "Sacred Heart Clinic",
//   "121": "Sango PHC",
//   "122": "Sari PHC",
//   "123": "Saseun Hosp.&Maternity",
//   "124": "Seme PHC",
//   "125": "Shammah Specialist Hosp.",
//   "126": "Shomolu GH",
//   "127": "Simpson PHC",
//   "128": "Soretire PHC",
//   "129": "St Raphael Divine Mercy Specialist Hosp.",
//   "130": "St.Catherine of Siena Medical Centre-Mafoluku",
//   "131": "St.Joseph Mission Clinic Kirikiri",
//   "132": "St.Kizito Clinic",
//   "133": "St.Leo Medical Centre",
//   "134": "St.Milla Hosp.",
//   "135": "Sura PHC",
//   "136": "Syban Medical Centre",
//   "137": "Tolu Medical Centre",
//   "138": "Tolu PHC",
//   "139": "Unita Hosp.",
//   "140": "Wright PHC",
// };
//
// final Nasarawa = {
//   "1": "Aboki Clinic",
//   "2": "Adogi PHC",
//   "3": "Adonai Hosp.",
//   "4": "Agu Hosp.",
//   "5": "Akwanga GH",
//   "6": "Akwanga PHC Center",
//   "7": "Alheri Clinic&Maternity",
//   "8": "Alheri Clinic&Maternity_U Turn(Karu)",
//   "9": "Alpha Medical Center",
//   "10": "Alushi ERCC",
//   "11": "Amosun Maternity Hosp.",
//   "12": "Andaha PHC Center",
//   "13": "Anguwan Waje PHC",
//   "14": "Anointed Clinic",
//   "15": "Ara 2 PHC",
//   "16": "Arumangye Bosco PHC",
//   "17": "Aso Panda PHC Center",
//   "18": "Assakio PHC",
//   "19": "Auta PHC",
//   "20": "Awe GH",
//   "21": "Azomeh Clinic",
//   "22": "Azuba Bashayi PHC",
//   "23": "Barkin Abdullahi PHC",
//   "24": "Best Clinic",
//   "25": "Burum-Burum PHC",
//   "26": "Cath. Maternity&Rural Health Center -Agwatashi",
//   "27": "Chelsea Clinic",
//   "28": "CPHC Kwandere",
//   "29": "Dalhatu Araf Specialist Hosp.",
//   "30": "Diamond Clinic-Lafiya",
//   "31": "Doma GH",
//   "32": "Doma PHC",
//   "33": "Doma Road PHC Center",
//   "34": "(ERCC) Clinic-Keffi",
//   "35": "(ERCC) Clinic-Murya",
//   "36": "Favour Clinic",
//   "37": "FMC-Keffi",
//   "38": "Garaku GH",
//   "39": "GH Mararaba Odege",
//   "40": "GH Panda",
//   "41": "Gidan Maiakuya PHC",
//   "42": "Gidan Zakara PHC",
//   "43": "Gora PHC",
//   "44": "Gosha Clinic&Maternity",
//   "45": "Graceland Clinic-Lafiya",
//   "46": "Gudi PHC Center",
//   "47": "Gunduma PHC",
//   "48": "Heartland Alliance Foundation",
//   "49": "Henad Medical Center",
//   "50": "Idadu PHC",
//   "51": "Ikon Allah Iroh Hosp.",
//   "52": "Imani Clinic",
//   "53": "Imani Clinic",
//   "54": "Imon PHC",
//   "55": "Innovative Biotech",
//   "56": "Jankanwa PHC",
//   "57": "Jatau Clinic",
//   "58": "Kadarko National PHC-Giza Dev Area",
//   "59": "Karu KP OSS",
//   "60": "Karu PHC",
//   "61": "Keana GH",
//   "62": "Keffi GH",
//   "63": "K-Health",
//   "64": "Kingscare Hosp.",
//   "65": "Kowa Hosp.",
//   "66": "Kowa Hosp.",
//   "67": "Kpamu Shammah Hosp.",
//   "68": "KPIF_Akwanga OSS",
//   "69": "KPIF_Karu OSS",
//   "70": "Lafia Clinic",
//   "71": "Lafia KP OSS",
//   "72": "Laminga PHC",
//   "73": "Loko 2 Kekura Road PHC",
//   "74": "Loko PHC",
//   "75": "M&D Hosp.",
//   "76": "Main Town Nasarawa PHC",
//   "77": "Mak-lin Clinic",
//   "78": "Maraba Clinic&Maternity",
//   "79": "Maraba Gurku PHC",
//   "80": "Mararaba Guruku Medical Center",
//   "81": "Mararaba Odege PHC Center",
//   "82": "Marmara PHC",
//   "83": "Masaka Central",
//   "84": "Masaka PHC",
//   "85": "Mayday Specialist Hosp.&Maternity",
//   "86": "Minlap Clinic",
//   "87": "Mission Hopsital",
//   "88": "Mochu Clinic",
//   "89": "Model PHC Agwada",
//   "90": "Mother&Child Welfare Clinic 1",
//   "91": "na Akwanga",
//   "92": "na Awe",
//   "93": "na Doma",
//   "94": "na Karu",
//   "95": "na Keana",
//   "96": "na Keffi",
//   "97": "na Kokona",
//   "98": "na Lafia",
//   "99": "na Nasarawa",
//   "100": "na Nasarawa Eggon",
//   "101": "na Nasarawa GH",
//   "102": "na Obi",
//   "103": "na Obi GH",
//   "104": "na Toto",
//   "105": "Nakowa Clinic",
//   "106": "Namu Clinic",
//   "107": "Nasara Clinic,Ara",
//   "108": "Nasarawa Eggon GH",
//   "109": "Nasarawa Medical Center",
//   "110": "New Era Clinic",
//   "111": "New Market Road PHC",
//   "112": "Nisi Hosp.",
//   "113": "Nunku PHC Center",
//   "114": "Nyanya Gbagi PHC Center",
//   "115": "Obi PHC Center-Agyragu",
//   "116": "Ojone Favour",
//   "117": "Okpatte PHC",
//   "118": "Olivet Medical Center",
//   "119": "Omatdefu Clinic&Maternity",
//   "120": "Orient Hosp.",
//   "121": "Oshyegba Medical Center",
//   "122": "Our Lady of Apostles Hosp.-Akwanga",
//   "123": "Owoche Clinic&Maternity",
//   "124": "PHC 1 Garaku",
//   "125": "PHC Agyaraku",
//   "126": "PHC Amiri",
//   "127": "PHC Azara",
//   "128": "PHC Bassa",
//   "129": "PHC Dari",
//   "130": "PHC Gadabuke",
//   "131": "PHC Gwagi",
//   "132": "PHC Gwandara",
//   "133": "PHC Gwanje",
//   "134": "PHC Kadarko",
//   "135": "PHC Keffi Anwa nizo",
//   "136": "PHC Kekura",
//   "137": "PHC Kofa Pada",
//   "138": "PHC kofar Gwanri",
//   "139": "PHC Kokona",
//   "140": "PHC Kpukpawu",
//   "141": "PHC Kwara",
//   "142": "PHC Nakere",
//   "143": "PHC Nasarawa Eggon",
//   "144": "PHC Nasarawa Toto",
//   "145": "PHC Panda",
//   "146": "PHC Sabongida",
//   "147": "PHC Sisim Baki",
//   "148": "PHC Tabu",
//   "149": "PHC Tudun Kauri",
//   "150": "PHC Tunga ",
//   "151": "PHC Uke",
//   "152": "PHC Wulko",
//   "153": "Pijag Maternity Home",
//   "154": "Rinze PHC Center",
//   "155": "Royal Hosp.",
//   "156": "Rukubi PHC",
//   "157": "Sabo Clinic",
//   "158": "Sadanji Medical Center",
//   "159": "Sauki Hosp.",
//   "160": "Shabu Model Comprehensive Center",
//   "161": "Shalom Clinic",
//   "162": "Shukura Specialist Hosp.",
//   "163": "St.Bernards Clinic-Akanga",
//   "164": "Tamaiko Clinic",
//   "165": "The Chrane Hosp.",
//   "166": "Toto GH",
//   "167": "Tudun Adabu PHC",
//   "168": "Tudun Gwandara PHC",
//   "169": "Tundun Wada",
//   "170": "Uke GH",
//   "171": "Umaisha GH",
//   "172": "Vicar Clinic",
//   "173": "Voice of Islam Hosp.",
//   "174": "Wadata PHC",
//   "175": "Wamba GH",
//   "176": "Zumunta Yelwa Ediya Clinic",
// };
//
// final Niger = {
//   "1": "Agaie GH",
//   "2": "Al-Azeez Medical Centre Kontagora",
//   "3": "Aminu Isah Kontagora GH Bangi",
//   "4": "B. H. C.- PANDOGARI",
//   "5": "BABANNA BHC",
//   "6": "BASE MEDICAL CENTRE",
//   "7": "BASIC HEALTH BEJI",
//   "8": "BHC N WUSE",
//   "9": "CHC MAJE",
//   "10": "CHC ZUNGERU",
//   "11": "CITIZEN HOSP",
//   "12": "CHC LAPAI",
//   "13": "DIJE BALA PHC CLINIC",
//   "14": "DISPENSARY- AGWARA",
//   "15": "DIVINE MERCY CLINIC",
//   "16": "Family Medicine Practice Centre-Gawubabangida",
//   "17": "FARY GROUP CLINIC",
//   "18": "FMC-Bida",
//   "19": "G. HOSP MOKWA",
//   "20": "GENERAL HOSP KUTIGI KUTIGI",
//   "21": "GH-Kagara",
//   "22": "GH-Lapai",
//   "23": "GH-Minna",
//   "24": "GH-New Bussa",
//   "25": "GH-Suleja",
//   "26": "GH  T MAGAJIYA",
//   "27": "GH -Bida",
//   "28": "GH Kontagora",
//   "29": "Clinic- TEGINA",
//   "30": "IbrahBabangida Specialist Hosp.-Minna",
//   "31": "LIBERTY HOSP",
//   "32": "LUCAS HOPSITAL",
//   "33": "MADALLA MEMDICAL CENTRE",
//   "34": "Mariga BHC",
//   "35": "MCH GULU",
//   "36": "MCH II",
//   "37": "MCH K KORO",
//   "38": "MCH RIJAU",
//   "39": "Minna OSS",
//   "40": "NCMS C DOKI",
//   "41": "OLD AIRPORT CLINIC",
//   "42": "PHC BOSSO SEC.",
//   "43": "PHC CLINIC GGWAZUNU",
//   "44": "PHC KWAMBA",
//   "45": "PHC PKAGUNGU",
//   "46": "PHC TUNGAN WAYA",
//   "47": "PPFN CLINIC",
//   "48": "RURAL HOSP",
//   "49": "RURAL HOSP- AUNA",
//   "50": "RURAL HOSP WUSHISHI",
//   "51": "RURAL Hosp. S PAWA",
//   "52": "SAVANAH Hosp.",
//   "53": "SHEHU SHAGARI GH NASKO",
//   "54": "STANDARD Hosp.",
//   "55": "SUPREME CLINIC",
//   "56": "SUZAN HOPSITAL",
//   "57": "TALBA CLINIC",
//   "58": "TOP MEDICAL Hosp.",
//   "59": "TOWN CLINIC",
//   "60": "UKASON PHC CLINIC",
//   "61": "Umaru YarAdua Memorial Hosp.-Sabonwuse",
//   "62": "WAWA BHC",
// };
//
// final Ogun = {
//   "1": "Agbado PHC Center",
//   "2": "Atan Model PHC",
//   "3": "Ayetoro GH",
//   "4": "FMC-Abeokuta",
//   "5": "Idi Iroko GH",
//   "6": "Ifo GH",
//   "7": "Ijebu Ife GH",
//   "8": "Ijoko PHC",
//   "9": "Imeko PHC",
//   "10": "Isaga Owode Health Center",
//   "11": "Isara State Hosp.",
//   "12": "Jesus is Love&Power Cath. Hosp.-Ifo",
//   "13": "Makun PHC",
//   "14": "Obafemi Owode GH",
//   "15": "Ofada Clinic",
//   "16": "og Abeokuta North",
//   "17": "og Abeokuta South",
//   "18": "og Ado-Odo Ota",
//   "19": "og Ewekoro",
//   "20": "og Ifo",
//   "21": "og Ijebu East",
//   "22": "og Ijebu North",
//   "23": "og Ijebu North East",
//   "24": "og Ijebu Ode",
//   "25": "og Ikenne",
//   "26": "og Imeko-Afon",
//   "27": "og Ipokia",
//   "28": "og Obafemi Owode",
//   "29": "og Odeda",
//   "30": "og Odogbolu",
//   "31": "og Ogun Waterside",
//   "32": "og Remo North",
//   "33": "og Sagamu",
//   "34": "og St Joseph Cath. Hosp.,Ijebu Igbo",
//   "35": "og State Hosp.,Abeokuta",
//   "36": "og State Hosp.,Ota",
//   "37": "og Yewa North",
//   "38": "og Yewa South",
//   "39": "Ogere PHC-Ikenne",
//   "40": "Ogijo PHC",
//   "41": "Olabisi Onabanjo UNTHosp",
//   "42": "Ota PHC",
//   "43": "Sabo PHC Center",
//   "44": "Sacred Heart Cath. Hosp.,Abeokuta",
//   "45": "Sango Ota PHC",
//   "46": "Specialist Hosp.-Ilaro",
//   "47": "St.Mary's Clinic-Ajilete",
//   "48": "State Hosp.-Ijebu Ode",
// };
//
// final Ondo = {
//   "1": "Arakale CHC",
//   "2": "Bolorunduro GH",
//   "3": "FMC-Owo",
//   "4": "First Mercy Specialist Hosp.",
//   "5": "Idanre GH",
//   "6": "Ido-Ani GH",
//   "7": "Ifon Basic Health Center",
//   "8": "Igbara Oke GH",
//   "9": "Igbokoda GH",
//   "10": "Igbotako GH",
//   "11": "Iju Itaogbolu GH",
//   "12": "Ile-Oluji GH",
//   "13": "Ipe Akoko GH",
//   "14": "Irun Akoko GH",
//   "15": "Isaipen Basic Health Center",
//   "16": "Iwaro-Oka GH-Akoko",
//   "17": "Moferere-Oja CHC",
//   "18": "Mother&Child Hosp.-Akure",
//   "19": "Mother&Child Hosp.-Ondo",
//   "20": "Oba-Ile CHC",
//   "21": "Ode Irele GH",
//   "22": "Ode-Irele CHC",
//   "23": "Okitipupa State Specialist Hosp.",
//   "24": "on Akoko North East",
//   "25": "on Akoko North West",
//   "26": "on Akoko South East",
//   "27": "on Akoko South West",
//   "28": "on Akure North",
//   "29": "on Akure South",
//   "30": "on Ese Odo",
//   "31": "on Idanre",
//   "32": "on Ifedore",
//   "33": "on Ilaje",
//   "34": "on Ile Oluji Okeigbo",
//   "35": "on Irele",
//   "36": "on Odigbo",
//   "37": "on Okitipupa",
//   "38": "on Ondo East",
//   "39": "on Ondo West",
//   "40": "on Ose",
//   "41": "on Owo",
//   "42": "Ore GH",
//   "43": "Owo GH",
//   "44": "St.Catherine's Hosp.-Iwaro-Oka",
//   "45": "State Specialist Hosp.-Akure",
//   "46": "State Specialist Hosp.-Ikare",
//   "47": "State Specialist Hosp.-Ondo",
//   "48": "Supare Model PHC",
// };
//
// final Osun = {
//   "1": "Cath. Hosp.&Maternity-Okeola",
//   "2": "Ede Specialist Hosp.",
//   "3": "Ejigbo Baptist Hosp.",
//   "4": "Ijebu-Ijesha GH",
//   "5": "Ikire Specialist Hosp.",
//   "6": "Ila Orangun State Hosp.",
//   "7": "Ilesa GH",
//   "8": "Ladoke Akintola Teaching Hosp.-Oshogbo",
//   "9": "Obafemi Awolowo UNTHosp Complex",
//   "10": "Oke-Ogbo GH,Ile Ife",
//   "11": "os Aiyedade",
//   "12": "os Aiyedire",
//   "13": "os Atakunmosa East",
//   "14": "os Atakunmosa West",
//   "15": "os Boluwaduro",
//   "16": "os Boripe",
//   "17": "os Ede North",
//   "18": "os Ede South",
//   "19": "os Egbedore",
//   "20": "os Ejigbo",
//   "21": "os Ife Central",
//   "22": "os Ife East",
//   "23": "os Ife North",
//   "24": "os Ife South",
//   "25": "os Ifedayo",
//   "26": "os Ifelodun",
//   "27": "os Ila",
//   "28": "os Ilesa East",
//   "29": "os Ilesa West",
//   "30": "os Irepodun",
//   "31": "os Irewole",
//   "32": "os Isokan",
//   "33": "os Iwo",
//   "34": "os Obokun",
//   "35": "os Odo Otin",
//   "36": "os Ola Oluwa",
//   "37": "os Olorunda",
//   "38": "os Oriade",
//   "39": "os Orolu",
//   "40": "os Osogbo",
//   "41": "os State Hosp.,Asubiaro",
//   "42": "Our Lady of Fatima Cath. Hosp.-Jaleyemi",
//   "43": "Our Lady of Lourdes Hosp.-Ipetumodun",
//   "44": "Seventh Day Adventist Hosp.-Ile-Ife",
//   "45": "State Hosp.-Iwo",
//   "46": "Victory Specialist Hosp.,Iwo",
// };
//
// final Oyo = {
//   "1": "Aafin PHC",
//   "2": "Aba Emu PHC",
//   "3": "Abogunde Baaki Health Center",
//   "4": "Adaramagbo Olomi PHC",
//   "5": "Adeoyo Maternity Hosp.",
//   "6": "Alafara Oje PHC",
//   "7": "Alegongo PHC",
//   "8": "Angel Hosp.",
//   "9": "Anjorin PHC",
//   "10": "Apete PHC",
//   "11": "Ayeye Maternity Health Center",
//   "12": "Baptist Medical Center-Saki",
//   "13": "Bowen UNTHosp(BUTH),Ogbomosho",
//   "14": "Comfort Medical Centre,Oyo",
//   "15": "Duro-Oyedoyin PHC",
//   "16": "Eruwa GH",
//   "17": "First Faith Medical Centre",
//   "18": "Hero Medical Centre",
//   "19": "Ibadan Central Hosp.,Ibadan",
//   "20": "Idi Ogungun PHC",
//   "21": "Igbeti GH",
//   "22": "Igboho GH",
//   "23": "Igbole PHC",
//   "24": "Ikoyi-Ile PHC",
//   "25": "Ilora GH",
//   "26": "Iseyin GH",
//   "27": "Iwo Road PHC",
//   "28": "Jericho Specialist Hosp.",
//   "29": "Kisi GH",
//   "30": "Lad Medical Centre,Ibadan",
//   "31": "Monatan PHC",
//   "32": "Moniya PHC",
//   "33": "Oba Adeyemi PHC",
//   "34": "Odinjo PHC",
//   "35": "Ogbomosho State Hosp.",
//   "36": "Ojoo PHC",
//   "37": "Okeho GH",
//   "38": "Olaniba Memorial Centre",
//   "39": "Olugbon Medical Centre,Igboora",
//   "40": "Oniyanrin PHC",
//   "41": "Oranyan PHC",
//   "42": "Ori Eru PHC",
//   "43": "Orile PHC",
//   "44": "Our Lady's Cath. Hosp.-Iseyin",
//   "45": "oy Afijio",
//   "46": "oy Akinyele",
//   "47": "oy Atiba",
//   "48": "oy Atisbo",
//   "49": "oy Egbeda",
//   "50": "oy Ibadan North",
//   "51": "oy Ibadan North-East",
//   "52": "oy Ibadan North-West",
//   "53": "oy Ibadan South-East",
//   "54": "oy Ibadan South-West",
//   "55": "oy Ibarapa Central",
//   "56": "oy Ibarapa East",
//   "57": "oy Ibarapa North",
//   "58": "oy Ido",
//   "59": "oy Irepo",
//   "60": "oy Iseyin",
//   "61": "oy Itesiwaju",
//   "62": "oy Iwajowa",
//   "63": "oy Kajola",
//   "64": "oy Lagelu",
//   "65": "oy Ogbomosho North",
//   "66": "oy Ogbomosho South",
//   "67": "oy Ogo Oluwa",
//   "68": "oy OLA Cath. Hosp.,Oluyoro,Ibadan",
//   "69": "oy Olorunsogo",
//   "70": "oy Oluyole",
//   "71": "oy Ona Ara",
//   "72": "oy Orelope",
//   "73": "oy Ori Ire",
//   "74": "oy Oyo East",
//   "75": "oy Oyo State OSS(OSS),Ibadan",
//   "76": "oy Oyo West",
//   "77": "oy Saki East",
//   "78": "oy Saki West",
//   "79": "oy State Hosp.,Oyo",
//   "80": "oy State Hosp.,Saki",
//   "81": "oy Surulere",
//   "82": "Oyo State OSS(OSS),Ibadan",
//   "83": "Ring Road State Hosp.",
//   "84": "Salus Infirmorum Cath. Hosp.",
//   "85": "Shekina Medical Centre,Oyo",
//   "86": "St.Anne's Anglican Hosp.-Molete Ibadan",
//   "87": "St.Dominics Cath. Hosp.-Ogungbade",
//   "88": "St.Mary's Cath. Hosp.-Eleta",
//   "89": "St.Peters GH-Aremo",
//   "90": "Surulere Able God Hosital",
//   "91": "Surulere Mezonel Hosp.",
//   "92": "Surulere The Family Clinic",
//   "93": "University College Hosp.",
// };
//
// final Plateau = {
//   "1": "Amper Central PHC Center",
//   "2": "Angware GH",
//   "3": "Barkin Ladi GH",
//   "4": "Bassa Cottage Hosp.",
//   "5": "Bingham UNTHosp",
//   "6": "Bokkos Cottage Hosp.",
//   "7": "Bukuru Express PHC",
//   "8": "CCDP Hosp.-Panyam",
//   "9": "(COCIN) Clinic-Gyel-Bukuru",
//   "10": "(COCIN) Hosp.&rehab Center",
//   "11": "Dadin Kowa CHC",
//   "12": "Dengi GH",
//   "13": "(ECWA) Comprehensive Hosp.-Bukuru",
//   "14": "Faith Alive Foundation",
//   "15": "Hwolshe Medical Center",
//   "16": "Jos UNTHosp",
//   "17": "Kombun PHC",
//   "18": "Kwalla GH",
//   "19": "Lardang CHC",
//   "20": "Lardang CHC",
//   "21": "Mangu GH",
//   "22": "May Hosp.-Shendam",
//   "23": "Our Lady of Apostle(OLA) Hosp.-Jos",
//   "24": "Our Lady of Apostles Hosp.&Orphanage,Zawan",
//   "25": "Pankshin GH",
//   "26": "pl Barkin Ladi",
//   "27": "pl Bassa",
//   "28": "pl Bokkos",
//   "29": "pl Jos East",
//   "30": "pl Jos North",
//   "31": "pl Jos South",
//   "32": "pl Kanam",
//   "33": "pl Kanke",
//   "34": "pl Langtang GH",
//   "35": "pl Langtang North",
//   "36": "pl Langtang South",
//   "37": "pl Mangu",
//   "38": "pl Mikang",
//   "39": "pl Pankshin",
//   "40": "pl Quaan Pan",
//   "41": "pl Riyom",
//   "42": "pl Shendam",
//   "43": "pl Wase",
//   "44": "Plateau State OSS(OSS),Jos",
//   "45": "Plateau State Specialist Hosp.",
//   "46": "Seventh Day Adventist(SDA) Hosp.-Jengre",
//   "47": "Shendam A PHC",
//   "48": "Shendam GH",
//   "49": "Solat Women Hosp.",
//   "50": "St.Virgillus Cath. Rural Health Center",
//   "51": "Tundun Wada PHC",
//   "52": "Tunkus GH",
//   "53": "Vom Christian Hosp.",
//   "54": "Zamko CHC",
// };
//
// final Rivers = {
//   "1": "Abonnema CHC",
//   "2": "Abua GH",
//   "3": "Agbonchia Model PHC",
//   "4": "Ahoada Gbeye Clinic Annex",
//   "5": "Ahoada GH",
//   "6": "Ahoada Model PHC",
//   "7": "Akpajo Model PHC",
//   "8": "Alphonso Hosp.",
//   "9": "Aluu Model PHC",
//   "10": "April Clinic",
//   "11": "Atinu Critical Care Hosp.",
//   "12": "Ayungu Biri Model PHC",
//   "13": "Bangoi PHC",
//   "14": "Beeri Model PHC",
//   "15": "Bodo GH",
//   "16": "Bomu Model PHC",
//   "17": "Bonny GH",
//   "18": "Bonny Health Centre",
//   "19": "Bonny KP OSS",
//   "20": "Bori GH",
//   "21": "Bori Inadum Medical Centre",
//   "22": "Braithwaite Memorial Specialist Hosp.",
//   "23": "Buguma Model PHC",
//   "24": "Bunduama Model PHC",
//   "25": "Bunu Model PHC",
//   "26": "Churchill Model PHC",
//   "27": "College of Health Technology Clinic",
//   "28": "Degema GH",
//   "29": "Divine Wisdom Hosp.",
//   "30": "Dorkson Medical Clinic",
//   "31": "Dumkil Medical Centre",
//   "32": "Ebubu Model PHC",
//   "33": "Elekahia Model PHC",
//   "34": "Elelenwo FSP Health Centre",
//   "35": "Eleme GH",
//   "36": "Eliozu Model PHC",
//   "37": "Eneka Model PHC",
//   "38": "Erema GH",
//   "39": "Gbeye Clinic",
//   "40": "Health of the Sick",
//   "41": "Hearth Health Hosp.",
//   "42": "Heritage Medicare Hosp.",
//   "43": "Ibaka Model PHC",
//   "44": "Igwuruta Model Health Center",
//   "45": "Initiative for Advancement of Humanity(IAH)",
//   "46": "Iriebe PHC",
//   "47": "Isiokpo GH",
//   "48": "Joinkrama GH",
//   "49": "Karpearl Hosp.",
//   "50": "Kendox Medical Services",
//   "51": "KPIF Obio-Akpor KP OSS",
//   "52": "KPIF_Obio-Akpor KP OSS",
//   "53": "Kpite Model PHC",
//   "54": "Kpor Model PHC",
//   "55": "Lengro Medical Centre",
//   "56": "Living Water Hosp.",
//   "57": "Mbodo Aluu PHC",
//   "58": "Megacare Hosp.",
//   "59": "Meridian Hosp.",
//   "60": "Mgbundukwu(Okija) Model PHC",
//   "61": "Morning Star Hosp.",
//   "62": "Morning Star Hosp.",
//   "63": "Nchia Health Centre",
//   "64": "Ndele Model PHC",
//   "65": "New Mile one Hosp.",
//   "66": "Ngo GH",
//   "67": "Nonwa Model PHC",
//   "68": "Obio Cottage Hosp.",
//   "69": "Obioha Model PHC",
//   "70": "Ogoloma Model PHC",
//   "71": "Ogu PHC",
//   "72": "Okomoko GH",
//   "73": "Okrika GH",
//   "74": "Okrika Mainland Clinic",
//   "75": "Okujagu Health Centre",
//   "76": "Okuru-ama Model PHC",
//   "77": "Okwuzi Model PHC",
//   "78": "Omas Medical Centre&Maternity",
//   "79": "Omoku GH",
//   "80": "Omoku Model PHC",
//   "81": "Omoku Prize Medicals Limited",
//   "82": "Onne Medical Centre",
//   "83": "Onne Model PHC",
//   "84": "Opobo GH",
//   "85": "Opuoko Model PHC",
//   "86": "Orogbum PHC",
//   "87": "Oyigbo CHC",
//   "88": "Ozuboko Model PHC",
//   "89": "Ozuoba Model PHC",
//   "90": "Palmers Hosp. Ltd",
//   "91": "Pathfare Clinic",
//   "92": "Police Medical Clinic",
//   "93": "Pope John Paul Clinic",
//   "94": "Potts Johnson Model PHC",
//   "95": "Resource Centre",
//   "96": "Rivon Clnic",
//   "97": "Rumueme Model PHC",
//   "98": "Rumuepirikom Model PHC",
//   "99": "Rumuigbo Model PHC",
//   "100": "Rumuji Model PHC",
//   "101": "Rumuodomaya Model PHC",
//   "102": "Rumuokrushi Model PHC",
//   "103": "Rumuolumeni Model PHC",
//   "104": "Sonabel Hosp.(HQ)",
//   "105": "Sonabel Medical Centre&Hosp.",
//   "106": "Splendour Hosp. Ltd",
//   "107": "Spring Hosp.",
//   "108": "St Matthews Clinic",
//   "109": "St Patricks Hosp.",
//   "110": "St.Charles Surgery",
//   "111": "St.Martin's Hosp.",
//   "112": "St.Peter's Clinic",
//   "113": "Sterling Specialist Hosp.",
//   "114": "Terrebor GH",
//   "115": "Ula Upata Beulah Clinic",
//   "116": "Umuebule Cottage Hosp.",
//   "117": "University of Portharcourt Teaching Hosp.",
//   "118": "Vinkas Clinic",
//   "119": "Woji Cottage Hosp.",
// };
//
// final Sokoto = {
//   "1": "Amanawa Lep General Hosp",
//   "2": "GH  Dogon Daji",
//   "3": "GH Tambuwal",
//   "4": "GH Yabo",
//   "5": "Holy Family Clinic",
//   "6": "Isah GH",
//   "7": "Maryam Abacha Women&Children Hosp.",
//   "8": "Rabah GH",
//   "9": "Sanyinna CHC",
//   "10": "so Illela GH",
//   "11": "so Kofar Rini CHC",
//   "12": "Sokoto Specialist Hosp.-Sokoto",
//   "13": "Usmanu Danfodiyyo UNTHosp(UDUTH)-Sokoto",
//   "14": "Women&Children Welfare Clinic",
//   "15": "Wurno GH",
// };
//
// final Taraba = {
//   "1": "First Referral Hosp. Lau",
//   "2": "FMC JALINGO",
//   "3": "FRH BAISSA",
//   "4": "FRH DONGA",
//   "5": "FRH IBI",
//   "6": "FRH KPANTISAWA",
//   "7": "FRH SERTI",
//   "8": "FRH SUNKANI",
//   "9": "GECHAAN LIFE CENTER GEMBU",
//   "10": "GH Takum ROGO WARD",
//   "11": "GH BALI",
//   "12": "GH BAMBUR",
//   "13": "GH GEMBU",
//   "14": "GH WAR WAR",
//   "15": "GH WUKARI",
//   "16": "GHC JALINGO",
//   "17": "MBH GEMBU .A .WARD",
//   "18": "SANCTA MARIA Clinic BALI",
//   "19": "ST MONIC YAKOKO",
//   "20": "Sunshine Clinic&Maternity",
//   "21": "ta Jinya Medical Centre",
//   "22": "ta Kwararafa Hosp.&Maternity",
//   "23": "ta Mutum Biyu First Referral Hosp.",
//   "24": "ta Rapha Hosp.",
//   "25": "ta Zing GH",
//   "26": "Taraba State OSS(OSS),Jalingo",
//   "27": "TSSH SINTALI B WARD",
//   "28": "UMCN ZING",
//   "29": "UMMAH CLINIC JALINGO",
//   "30": "Wukari CRCN CHC",
// };
//
// final Yobe = {
//   "1": "Fika GH",
//   "2": "Gashua GH",
//   "3": "Geidem GH",
//   "4": "Jakusko GH",
//   "5": "Nguru FMC",
//   "6": "Potiskum GH",
//   "7": "yo Sani Abacha Specialist Hosp.,Damaturu",
// };
//
// final Zamfara = {
//   "1": "Anka GH",
//   "2": "Bungudu GH",
//   "3": "FMC Gusau",
//   "4": "Gusau Gen Hosp",
//   "5": "Kaura Namoda GH",
//   "6": "King Fahad WCWC",
//   "7": "Mada PHC",
//   "8": "Magami PHC",
//   "9": "Maru GH",
//   "10": "Shagari Clinic",
//   "11": "Shinkafi Gen Hosp",
//   "12": "Tsafe General Hosp",
//   "13": "Tudun Wada MCH Clinic",
//   "14": "Yerima Bakura Specialist Hosp.",
//   "15": "za Gummi GH",
//   "16": "za Talata Mafara GH",
// };
//
// // State List for HQ/State office staff
//
// final StatesOfImplementation = ["FCT", "Abia", "Imo", "Enugu"];
//
// final OfficeLocation = ["Central Office-HQ", "State Office", "LGA Office"];
//
// final Abia_State = {
//   "1": "State Office",
//   "2": "LGA Office",
// };
//
// final Enugu_State = {
//   "1": "State Office",
//   "2": "LGA Office",
// };
//
// final Imo_State = {
//   "1": "State Office",
//   "2": "LGA Office",
// };
//
// final Abuja = {
//   "1": "Central Office-HQ",
// };
